### ISSUE TITLE
AttributeError: scores for making prediction on model=visual_bert using pretrain modal

### ISSUE THREAD

**Issue by Sicongzai** [facebookresearch/mmf#1028]
## 🐛 Bug

Hi. I would like to make a prediction on both model visual_bert and vilbert using pretrain modal on vqa2's test set. But have meet bugs on both models:

**1.  For Visual_bert**

Traceback (most recent call last):
  File "/usr/local/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/content/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/content/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/content/mmf/mmf/trainers/mmf_trainer.py", line 138, in train
    self.inference()
  File "/content/mmf/mmf/trainers/mmf_trainer.py", line 158, in inference
    self.prediction_loop(dataset)
  File "/content/mmf/mmf/trainers/core/evaluation_loop.py", line 142, in prediction_loop
    reporter.add_to_report(report, self.model)
  File "/content/mmf/mmf/common/test_reporter.py", line 211, in add_to_report
    results = self.current_dataset.format_for_prediction(report)
  File "/content/mmf/mmf/datasets/concat_dataset.py", line 35, in _call_all_datasets_func
    value = getattr(dataset, name)(*args, **kwargs)
  File "/content/mmf/mmf/datasets/builders/vqa2/dataset.py", line 151, in format_for_prediction
    answers = report.scores.argmax(dim=1)
  File "/content/mmf/mmf/common/report.py", line 79, in __getattr__
    raise AttributeError(key)
AttributeError: scores

When I use mmf_run instead, it can run successfully and give out the losses around 3.
**2.  For Vibert**
Traceback (most recent call last):
  File "/usr/local/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/content/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/content/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/content/mmf/mmf/trainers/mmf_trainer.py", line 138, in train
    self.inference()
  File "/content/mmf/mmf/trainers/mmf_trainer.py", line 158, in inference
    self.prediction_loop(dataset)
  File "/content/mmf/mmf/trainers/core/evaluation_loop.py", line 140, in prediction_loop
    model_output = self.model(prepared_batch)
  File "/content/mmf/mmf/models/base_model.py", line 273, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/mmf/mmf/models/vilbert.py", line 1448, in forward
    params["image_target"],
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/mmf/mmf/models/vilbert.py", line 1144, in forward
    F.log_softmax(prediction_scores_v, dim=2), image_target
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 462, in forward
    return F.kl_div(input, target, reduction=self.reduction, log_target=self.log_target)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2753, in kl_div
    reduced = torch.kl_div(input, target, reduction_enum, log_target=log_target)
RuntimeError: The size of tensor a (1600) must match the size of tensor b (1601) at non-singleton dimension 2

The same error when I used the command mmf_run
## Command
**1.  For Vibert**
!mmf_predict config=projects/visual_bert/configs/masked_vqa2/defaults.yaml \
        model=visual_bert \
        dataset=masked_vqa2 \
        run_type=val \
        env.cache_dir=/content/flickr30k/cache \
        env.data_dir=/content/drive/MyDrive/MSc_Project/dataset/VQA_MMF_processed/provided_by_MMF \
        env.save_dir=/content/drive/MyDrive/MSc_Project/Result/MMF/Visual_bert/masked_vqa2/val \
        training.num_workers=0 \
        training.batch_size=8 \
        training.update_frequency=64 \
        checkpoint.resume_zoo=vilbert.pretrained.vqa2

**1.  For Visual_bert**
!mmf_predict config=projects/vilbert/configs/masked_vqa2/defaults.yaml \
        model=vilbert \
        dataset=masked_vqa2 \
        run_type=val \
        env.cache_dir=/content/flickr30k/cache \
        env.data_dir=/content/drive/MyDrive/VQA_MMF_processed/provided_by_MMF \
        env.save_dir=/content/drive/MyDrive/Result/MMF/Visual_bert/masked_vqa2/val \
        training.num_workers=0 \
        training.batch_size=8 \
        training.update_frequency=64 \
        checkpoint.resume_zoo=vilbert.pretrained.vqa2

## Expected behavior

Expected to have prediction in .json format generated.

## Environment

I applied Colab.:
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7 (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.9.0+cu102
[pip3] torchmetrics==0.4.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu102
[conda] Could not collect

**Comment by yingying123321** [comment]
Could I ask a question? When we do inference, shoud we download the whole dataset of masked_vqa2 or test dataset?

**Comment by apsdehal** [comment]
Hi,
Please use `dataset=vqa2` when making predictions for VQA2. 

@yingying123321 Didn't get your question. You will need VQA 2 test dataset to make predictions on VQA 2.0. `masked_vqa2` uses vqa2 dataset but applies masking on it and hence doesn't have `scores` and other attributes in the report.
