### ISSUE TITLE
UNIT coco.single_task checksum of downloaded file does not match the expected checksum

### ISSUE THREAD

**Issue by Gugutse** [facebookresearch/mmf#1043]
## ❓ Questions and Help
Hi! Thanks for your work.
I'm trying to start UniT training on all 8 datasets with the initialization from a single-task model trained on COCO -- thus, I add `checkpoint.resume_zoo=unit.coco.single_task` to the training command. Unfortunately, I get a checksum error while downloading unit.coco.single_task.tar.gz:

`Traceback (most recent call last):
  File "mmf_cli/run.py", line 137, in <module>
    run()
  File "mmf_cli/run.py", line 129, in run
    nprocs=config.distributed.world_size,
  File "/home/user/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/user/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/trainers/mmf_trainer.py", line 46, in load
    self.on_init_start()
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/trainers/core/callback_hook.py", line 15, in on_init_start
    callback.on_init_start(**kwargs)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/trainers/callbacks/checkpoint.py", line 31, in on_init_start
    self._checkpoint.load_state_dict()
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/checkpoint.py", line 207, in load_state_dict
    load_pretrained=ckpt_config.resume_pretrained,
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/checkpoint.py", line 231, in _load
    ckpt, should_continue = self._load_from_zoo(file)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/checkpoint.py", line 437, in _load_from_zoo
    zoo_ckpt = load_pretrained_model(file)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/checkpoint.py", line 129, in load_pretrained_model
    return _load_pretrained_model(model_name_or_path_or_checkpoint, args, kwargs)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/checkpoint.py", line 76, in _load_pretrained_model
    download_path = download_pretrained_model(model_name_or_path, *args, **kwargs)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/download.py", line 378, in download_pretrained_model
    download_resources(resources, download_path, version)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/download.py", line 397, in download_resources
    download_resource(resource, download_path)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/download.py", line 406, in download_resource
    resource.download_file(download_path)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/download.py", line 161, in download_file
    self.checksum(download_path)
  File "/home/jovyan/quick-start/job_launch/mmf/mmf/utils/download.py", line 127, in checksum
    f"[ Checksum for {self._file_name} from \n{self._url}\n"
AssertionError: [ Checksum for unit.coco.single_task.tar.gz from 
https://dl.fbaipublicfiles.com/mmf/data/models/unit_models/unit.coco.single_task.tar.gz
does not match the expected checksum. Please try again. ]
`

**Comment by ronghanghu** [comment]
This seems a bit weird -- maybe this could be a network error?

The SHA256 sum for https://dl.fbaipublicfiles.com/mmf/data/models/unit_models/unit.coco.single_task.tar.gz should be `d235fe2d27b47d8f19ce82bea2b1bc6d33151b7c6c1a5558c2a501911b9f4880` as shown in https://github.com/facebookresearch/mmf/blob/master/mmf/configs/zoo/models.yaml#L509.

@Gugutse Could you try downloading this file locally and verify the checkpoint?

```
wget https://dl.fbaipublicfiles.com/mmf/data/models/unit_models/unit.coco.single_task.tar.gz
sha256sum unit.coco.single_task.tar.gz
```
(I just tried it myself and got the correct check sum `d235fe2d27b47d8f19ce82bea2b1bc6d33151b7c6c1a5558c2a501911b9f4880`)
