### ISSUE TITLE
BUTD model on VQA task

### ISSUE THREAD

**Issue by RishabhMaheshwary** [facebookresearch/mmf#1050]
## ❓ Questions and Help
I was trying to train BUTD model on vizwiz dataset but I got the following error:
```
Traceback (most recent call last):
  File "/scratch/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/scratch/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/scratch/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/scratch/mmf/mmf/trainers/mmf_trainer.py", line 148, in train
    self.training_loop()
  File "/scratch/mmf/mmf/trainers/core/training_loop.py", line 33, in training_loop
    self.run_training_epoch()
  File "/scratch/mmf/mmf/trainers/core/training_loop.py", line 91, in run_training_epoch
    report = self.run_training_batch(batch, num_batches_for_this_update)
  File "/scratch/mmf/mmf/trainers/core/training_loop.py", line 166, in run_training_batch
    report = self._forward(batch)
  File "/scratch/mmf/mmf/trainers/core/training_loop.py", line 200, in _forward
    model_output = self.model(prepared_batch)
  File "/scratch/mmf/mmf/models/base_model.py", line 278, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/scratch/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/scratch/mmf/mmf/models/butd.py", line 120, in forward
    scores = sample_list.answers.new_ones(
  File "/scratch/mmf/mmf/common/sample.py", line 166, in __getattr__
    "Valid choices are {}".format(key, self.fields())
AttributeError: Key answers not found in the SampleList. Valid choices are ['text', 'question_id', 'image_id', 'text_len', 'image_feature_0', 'image_info_0', 'targets', 'dataset_name', 'dataset_type']
```
I used the following config and command
Config:
```
model_config:
  butd: &butd
    model_data_dir: ${env.data_dir}
    losses:
    - type: caption_cross_entropy
    classifier:
      type: language_decoder
      params:
	dropout: 0.5
        hidden_dim: 1024
        feature_dim: 2048
        fc_bias_init: 0
    image_feature_embeddings:
    - modal_combine:
        type: top_down_attention_lstm
        params:
          dropout: 0.5
          hidden_dim: 1024
          attention_dim: 1024
      normalization: softmax
      transform:
        type: linear
        params:
          out_dim: 1
    image_feature_dim: 2048
    embedding_dim: 300
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
	bias_file: models/detectron.defaults/fc7_b.pkl
        weights_file: models/detectron.defaults/fc7_w.pkl
        model_data_dir: ${model_config.butd.model_data_dir}
dataset_config:
  vizwiz:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      zoo_requirements:
      - vizwiz.v2020
      features:
          train:
          - vizwiz2/train_features
          val:
          - vizwiz2/val_features
          test:
          - vizwiz2/val_features
      annotations:
          train:
          - vizwiz2/annotations_classification/imdb_vizwiz_train.npy
          val:
          - vizwiz2/annotations_classification/imdb_vizwiz_val.npy
          test:
          - vizwiz2/annotations_classification/imdb_vizwiz_val.npy
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: vizwiz2/extras/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
        answer_processor:
          type: vqa_answer
          params:
            vocab_file: vizwiz2/extras/vocabs/answers_vizwiz_classification.txt
            preprocessor:
              type: simple_word
              params: {}
            num_answers: 10
        context_processor:
          type: fasttext
          params:
            max_length: 50
            model_file: wiki.en.bin
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: true
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

evaluation:
  metrics:
  - vqa_accuracy

training:
  batch_size: 1
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  early_stop:
    criteria: vizwiz2/vqa_accuracy
    minimize: false
```

Command:

```
mmf_run config=vizwiz2_train.yaml \
  datasets=vizwiz  \
  model=butd run_type=train_val \
  env.data_dir="/scratch/mmf_data" \
  env.cache_dir="/scratch/mmf_cache" \
  env.save_dir="/scratch/mmf/save_butd" \
  training.find_unused_parameters=True \
  training.tensorboard=True
```

It seems like the BUTD model is implemented for captioning tasks and not for VQA task. 
How should I train the BUTD model for VQA task?

**Comment by apsdehal** [comment]
Hi @RishabhMaheshwary ,

Yes, BUTD model is not supposed to be used for VQA task. Please instead use Pythia model which is an extension of BUTD but better.

**Comment by RishabhMaheshwary** [comment]
Thanks for the reply!
