### ISSUE TITLE
KeyError raised while resolving interpolation: "Environment variable 'USER' not found"

### ISSUE THREAD

**Issue by TopCoder2K** [facebookresearch/mmf#1090]
## ❓ Questions and Help
Hello everyone!
I encountered a strange error when tried to run 
`mmf_predict config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=test \
    checkpoint.resume_zoo=m4c.textvqa.defaults`
The error is
```
2021-09-15T06:43:51 | matplotlib.font_manager: Generating new fontManager, this may take some time...
/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py:257: UserWarning: In the sequence `MMF_USER_DIR,` some elements are missing: please replace them with empty quoted strings. See https://github.com/omry/omegaconf/issues/572 for details.
  category=UserWarning,
/root/.local/lib/python3.7/site-packages/omegaconf/resolvers/__init__.py:13: UserWarning: The `env` resolver is deprecated, see https://github.com/omry/omegaconf/issues/573
  "The `env` resolver is deprecated, see https://github.com/omry/omegaconf/issues/573"
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option config to projects/m4c/configs/textvqa/defaults.yaml
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option datasets to textvqa
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option model to m4c
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option run_type to test
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option checkpoint.resume_zoo to m4c.textvqa.defaults
2021-09-15T06:43:52 | mmf.utils.configuration: Overriding option evaluation.predict to true
/content/mmf/mmf/utils/configuration.py:582: UserWarning: Device specified is 'cuda' but cuda is not present. Switching to CPU version.
  "Device specified is 'cuda' but cuda is not present. "
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/omegaconf/resolvers/oc/__init__.py", line 33, in env
    return os.environ[key]
  File "/root/anaconda3/envs/mmf/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1030, in accept
    return visitor.visitInterpolationResolver(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 182, in visitInterpolationResolver
    args_str=tuple(args_str),
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 653, in resolver_interpolation_callback
    inter_args_str=args_str,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 596, in _evaluate_custom_resolver
    inter_args_str,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 435, in resolver_wrapper
    ret = resolver(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/resolvers/oc/__init__.py", line 38, in env
    raise KeyError(f"Environment variable '{key}' not found")
KeyError: "Environment variable 'USER' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/mmf/bin/mmf_predict", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "/content/mmf/mmf_cli/predict.py", line 15, in predict
    run(predict=True)
  File "/content/mmf/mmf_cli/run.py", line 91, in run
    configuration = Configuration(args)
  File "/content/mmf/mmf/utils/configuration.py", line 349, in __init__
    OmegaConf.to_container(self.config, resolve=True)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 554, in to_container
    structured_config_mode=structured_config_mode,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 226, in _to_content
    structured_config_mode=structured_config_mode,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 226, in _to_content
    structured_config_mode=structured_config_mode,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 217, in _to_content
    node = node._dereference_node()
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 205, in _dereference_node
    node = self._dereference_node_impl(throw_on_resolution_failure=True)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 242, in _dereference_node_impl
    memo=memo,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 483, in _resolve_interpolation_from_parse_tree
    parse_tree=parse_tree, node=value, key=key, parent=parent, memo=memo
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 669, in resolve_parse_tree
    ).with_traceback(sys.exc_info()[2])
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 662, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 205, in accept
    return visitor.visitConfigValue(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 339, in accept
    return visitor.visitText(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/root/.local/lib/python3.7/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1030, in accept
    return visitor.visitInterpolationResolver(self)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/grammar_visitor.py", line 182, in visitInterpolationResolver
    args_str=tuple(args_str),
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 653, in resolver_interpolation_callback
    inter_args_str=args_str,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/base.py", line 596, in _evaluate_custom_resolver
    inter_args_str,
  File "/root/.local/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 435, in resolver_wrapper
    ret = resolver(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/omegaconf/resolvers/oc/__init__.py", line 38, in env
    raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'USER' not found"
```

I don't understand why 'USER' was not found... Do you have any ideas how to fix it?
I'm using Google Colab, and I installed conda on the machine. For mmf, I followed the [tutorial](https://mmf.sh/docs/):
```
!/root/anaconda3/bin/conda create -n mmf python=3.7
!git clone https://github.com/facebookresearch/mmf.git
%cd mmf
!source ~/anaconda3/bin/activate mmf && pip install --editable .
```

Many thanks!

**Comment by shwetkm** [comment]
@TopCoder2K I was having the same issue on Colab.
Runnig this before mmf_run command resolved the issue:
```
import os
os.environ['USER'] = 'any_user_name' 
```

**Comment by Ryan-Qiyu-Jiang** [comment]
Hi seems like exporting the env variable resolves this issue, going to close it! 
Feel free to reopen if it's unresolved.
