### ISSUE TITLE
Exit Status 1 Error during Install

### ISSUE THREAD

**Issue by versipellis** [facebookresearch/mmf#1119]
Tried all the different methods to do an install, not sure if this is erroring because I have multiple users with Python installed, or if it's a Python 2.7 issue - anyone know?

```
Defaulting to user installation because normal site-packages is not writeable                                          
Collecting git+https://github.com/facebookresearch/mmf.git                                                               
Cloning https://github.com/facebookresearch/mmf.git to /tmp/pip-req-build-tC9Ck1                                       
Running command git clone -q https://github.com/facebookresearch/mmf.git /tmp/pip-req-build-tC9Ck1                     
Installing build dependencies ... done                                                                                 
Getting requirements to build wheel ... error                                                                          
ERROR: Command errored out with exit status 1:                                                                          
command: /usr/bin/python /userdir/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsd0yDq                                                                            
cwd: /tmp/pip-req-build-tC9Ck1                                                                                    
Complete output (19 lines):                                                                                            
Traceback (most recent call last):                                                                                       
File "/userdir/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
                                                                                                                 main()                                                                                                               
File "/userdir/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
                                                                                                                     json_out['return_val'] = hook(**hook_input['kwargs'])                                                                
File "/userdir/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
                                                                                             return hook(config_settings)                                                                                         
File "/tmp/pip-build-env-uEpRYh/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
                                                                                                        return self._get_build_requires(config_settings, requirements=['wheel'])                                             
File "/tmp/pip-build-env-uEpRYh/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
                                                                                                                 self.run_setup()                                                                                                     
File "/tmp/pip-build-env-uEpRYh/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
                                                                                                                           self).run_setup(setup_script=setup_script)                                                                           
File "/tmp/pip-build-env-uEpRYh/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
                                                                                                                           exec(compile(code, __file__, 'exec'), locals())                                                                      
File "setup.py", line 72
                                                                                                 options = glob(f"{folder}/**", recursive=True)                                                                                                     ^                                                                                      
SyntaxError: invalid syntax                                                                                            
----------------------------------------                                                                             
ERROR: Command errored out with exit status 1: /usr/bin/python /userdir/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsd0yDq Check the logs for full command output. 
```

**Comment by versipellis** [comment]
Nevermind, PEBKAC - I didn't spot that it was trying to install with Python 2.7. Sorry!
