### ISSUE TITLE
ValueError: transformers.models.auto.__spec__ is None

### ISSUE THREAD

**Issue by Mayor2305** [facebookresearch/mmf#1189]
after running this command: mmf_convert_hm --zip_file=/home/jyotiradityamayor/Desktop/hateful_memes.zip --password=y --bypass_checksum=1

I have been getting value error.

log:

Traceback (most recent call last):
  File "/home/jyotiradityamayor/.local/bin/mmf_convert_hm", line 5, in <module>
    from mmf_cli.hm_convert import main
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf_cli/hm_convert.py", line 10, in <module>
    from mmf.utils.configuration import Configuration
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf/__init__.py", line 8, in <module>
    from mmf import utils, common, modules, datasets, models
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf/modules/__init__.py", line 3, in <module>
    import mmf.modules.metrics
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf/modules/metrics.py", line 53, in <module>
    from mmf.datasets.processors.processors import EvalAIAnswerProcessor
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf/datasets/__init__.py", line 4, in <module>
    from .base_dataset_builder import BaseDatasetBuilder
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/mmf/datasets/base_dataset_builder.py", line 40, in <module>
    import pytorch_lightning as pl
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate  # noqa: F401
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/functional/audio/pit.py", line 24, in <module>
    from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/utilities/imports.py", line 92, in <module>
    _TRANSFORMERS_AUTO_AVAILABLE = _module_available("transformers.models.auto")
  File "/home/jyotiradityamayor/.local/lib/python3.8/site-packages/torchmetrics/utilities/imports.py", line 36, in _module_available
    return find_spec(module_path) is not None
  File "/usr/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: transformers.models.auto.__spec__ is None

tried different versions of transformers but the error still persists.

**Comment by BrandonHanx** [comment]
This may be useful https://github.com/PyTorchLightning/pytorch-lightning/issues/11524

**Comment by WannaGetDSJobInSanFrancisco** [comment]
Met the same error, in my case when trying to reproduce [UniT tutorial](https://mmf.sh/docs/projects/unit/).
@BrandonHanx 's solution worked for me, and then `no module named future` popped up, and then [this page](https://stackoverflow.com/questions/49353905/no-module-named-future) resolved my problem.
