### ISSUE TITLE
Training crashing after ~2000 iterations

### ISSUE THREAD

**Issue by sarahallen111** [facebookresearch/mmf#144]
## ❓ Questions and Help
I am doing training on the captioning task using a new dataset (whose data has been formatted like the coco dataset). For the most part, training has been working fine; however, I seem to get an error about every ~2000 iterations very consistently. The error message always looks like the following (I'll post the full message down below):

`RuntimeError: Function 'X' returned nan values in its 0th output.`

Where 'X' has been a bunch of different functions, including:
- MmBackward (this is the one that typically gets displayed, but not always)
- WeightNormCudaInterfaceBackward
- torch::autograd::CopySlices
- PackPaddedSequenceBackward
and so on. 

When I restart the training from the checkpoint, it runs perfectly fine until it crashes after another ~2000 iterations. 

Normally this would be a minor (if annoying) bug, because I could just tell the trainer to start from the latest checkpoint and just restart it every time it crashes (2000 iterations is about 2 hours). However, when I tell it to restart from the latest checkpoint, it will always restart from the best checkpoint instead, which means that if it didn't come up with another "best" iteration in those 2000 iterations before it crashes, it will never progress further into the training.

What I mean is, if, say, the best iteration is 10,000 and the furthest is 12,000, and I run:
`CUDA_VISIBLE_DEVICES=0,1,2 python tools/run.py --tasks captioning --datasets cuhk --model butd --config configs/captioning/cuhk/butd2.yml --data_parallel 2 --device cuda --resume_file save/captioning_cuhk_butd_1234/models/model_12000.ckpt`
which points the the latest iteration (12000), it will still start at iteration 10000.

So, even if you don't have a quick answer for the main error, if you could tell me how to start at the desired iteration then I could just continue the training from there (restarting the process whenever the crash appears). Not the best solution, but at least it will finish.

An example of the full error can be seen below:

```
2019-08-05T00:38:09 WARNING: sys:1: RuntimeWarning: Traceback of forward call that caused the error:
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/scratch/sea97/allPythia/content/pythia/pythia/models/base_model.py", line 107, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sea97/allPythia/content/pythia/pythia/models/butd.py", line 145, in forward
    output = self.classifier(attention_feature)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sea97/allPythia/content/pythia/pythia/modules/layers.py", line 65, in forward
    return self.module(*args, **kwargs)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sea97/allPythia/content/pythia/pythia/modules/decoders.py", line 77, in forward
    predictions = self.fc(self.dropout(h2))
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/modules/module.py", line 485, in __call__
    hook(self, input)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/utils/weight_norm.py", line 55, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/nn/utils/weight_norm.py", line 18, in compute_weight
    return _weight_norm(v, g, self.dim)


2019-08-05T00:38:09 ERROR: Function 'WeightNormCudaInterfaceBackward' returned nan values in its 0th output.
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/scratch/sea97/allPythia/content/pythia/pythia/trainers/base_trainer.py", line 231, in train
    self._backward(loss)
  File "/scratch/sea97/allPythia/content/pythia/pythia/trainers/base_trainer.py", line 256, in _backward
    loss.backward()
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/sea97/anaconda3/envs/Pythia/lib/python3.7/site-packages/torch-1.0.1.post2-py3.7-linux-x86_64.egg/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'WeightNormCudaInterfaceBackward' returned nan values in its 0th output.
```

**Comment by apsdehal** [comment]
Even though it is saying 10000, technically it is at 12000th iteration because what we currently save in the checkpoint is the best iteration instead of current iteration. For now, you can assume that 10000th is the 12000th iteration. Let me think more about what we want to save inside the checkpoint. @vedanuj  Can you look into the other error?

**Comment by apsdehal** [comment]
My two cents: in most of the cases when this error happens it is due to very high learning rate. Try decreasing your learning rate and run again.

**Comment by sarahallen111** [comment]
I set my learning rate (lr) as the default value, which was 0.01, so it seems like it is pretty small already... but I suppose I could make it smaller? Though if changing the defaults means I have to start over with training, then I may just keep with what I have so I don't have to start over from scratch again.

**Comment by apsdehal** [comment]
Yeah, but you can override default learning rate by adding `optimizer_attributes.params.lr LR_VALUE_HERE`  at the end of your command or use lr scheduler. And people do decrease learning rate as they get close to the convergence point and it seems a good choice for you at the moment. Thus, you should try decreasing it.

**Comment by sarahallen111** [comment]
Could you give a recommendation of what value to set it to? I'm very new to machine learning so I don't really have a sense of it. 0.001? Smaller?

**Comment by vedanuj** [comment]
@sarahallen111 You seem to be using a different dataset. Are you sure there are no corrupt images in the dataset? Did you check running the training with COCO dataset and if the problem occurs with COCO?

**Comment by apsdehal** [comment]
And for LR, moving in the steps of 0.1 multiplier seems reasonable. Though, I will suggest reading more literature e.g. https://machinelearningmastery.com/learning-rate-for-deep-learning-neural-networks/

But, first, I will go through comments made by @vedanuj

**Comment by sarahallen111** [comment]
It is a new dataset, though I formatted the dataset to match the format of COCO. There shouldn't be any corrupt images in the dataset, because one of my lab partners did separate training (for another task) using it and it worked. 

I unfortunately was not able to do any training using the COCO dataset itself. The COCO dataset is large, and because of space concerns on our GPU server I couldn't try training with it. Since the new dataset is in a similar format to COCO, I only had to make minor changes to the various config files to get the training started. So I suppose it could just be something on my end while I was setting everything up.

**Comment by pidugusundeep** [comment]
@sarahallen111 Can you please let me know how did you create a dataset thats similar to coco format ? #175

**Comment by sarahallen111** [comment]
It was mostly a "copy whatever COCO is using" kind of job. I looked at the imdb files of COCO to make sure my dataset (what I called cuhk) was organized into the same format. Then I went through the code, copying whatever files were required, placing it into the appropriate spots (often in some captioning/cuhk folder) making as minimal changes as I could to get it to actually run (changing coco --> cuhk, making sure everything pointed to the right files, etc.)

Just to let you know, the training did end up finishing, I would just have to start it again after 2000 iterations. So far the model that was produced seems to be working alright. It was more annoying than anything, having to keep watch over the training processes so frequently.

**Comment by pidugusundeep** [comment]
how do I create the features set and `.npy` files for images and captions respectively?

**Comment by sarahallen111** [comment]
I can help you on the separate issue topic you posted, but you probably shouldn't be posting unrelated questions in other people's issues pages... You only put up the question like an hour ago, it takes time for people to respond.

**Comment by pidugusundeep** [comment]
You are correct will be waiting for people to respond to the new issue will remove my unrelated comments here as well

**Comment by apsdehal** [comment]
> Just to let you know, the training did end up finishing, I would just have to start it again after 2000 iterations. So far the model that was produced seems to be working alright. It was more annoying than anything, having to keep watch over the training processes so frequently.

FYI, a simple solution to this problem in general is to add a try-catch to "tools/run.py" and requeue your job with `--resume 1` :)
