### ISSUE TITLE
Restoring checkpoint error

### ISSUE THREAD

**Issue by SelinaFelton** [facebookresearch/mmf#185]
## ❓ Questions and Help
I met an error when training after the max iterations：

> 2019-10-12T20:02:44 INFO: textvqa: full val:, 26001/26000, val/total_loss: 9.5553, val/logit_bce: 9.5553, val/vqa_accuracy: 0.3055, validation time: 01m 25s 349ms, best iteration: 17000, best val/vqa_accuracy: 0.309980
2019-10-12T20:02:45 INFO: Restoring checkpoint
2019-10-12T20:02:49 ERROR: CUDA out of memory. Tried to allocate 39.12 MiB (GPU 0; 10.76 GiB total capacity; 9.71 GiB already allocated; 5.56 MiB free; 10.13 MiB cached)
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/B/gcy/code/pythia-master/pythia/trainers/base_trainer.py", line 237, in train
    self.finalize()
  File "/home/B/gcy/code/pythia-master/pythia/trainers/base_trainer.py", line 272, in finalize
    self.checkpoint.restore()
  File "/home/B/gcy/code/pythia-master/pythia/utils/checkpoint.py", line 242, in restore
    self.trainer.optimizer.load_state_dict(ckpt["optimizer"])
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/site-packages/torch/optim/optimizer.py", line 103, in load_state_dict
    state_dict = deepcopy(state_dict)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/site-packages/torch/tensor.py", line 26, in __deepcopy__
    new_storage = self.storage().__deepcopy__(memo)
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/site-packages/torch/storage.py", line 28, in __deepcopy__
    new_storage = self.clone()
  File "/home/gcy/anaconda3/envs/ye/lib/python3.6/site-packages/torch/storage.py", line 44, in clone
    return type(self)(self.size()).copy_(self)
RuntimeError: CUDA out of memory. Tried to allocate 39.12 MiB (GPU 0; 10.76 GiB total capacity; 9.71 GiB already allocated; 5.56 MiB free; 10.13 MiB cached)

How can I do with this error without setting my batch-size smaller?

**Comment by apsdehal** [comment]
That's seems odd. I think your GPU didn't had any memory left by the time if came to restore (it has to load two state_dicts at that time). I would suggest to resume with `--resume 1` and using `--run_type inference` to just run the inference.
