### ISSUE TITLE
load model fasttext issue

### ISSUE THREAD

**Issue by aluka1994** [facebookresearch/mmf#234]
while training, I am getting load model error. can you please help in training the model ? 

020-04-14T02:47:26 INFO: Starting training...
2020-04-14T02:47:27 INFO: Fetching fastText model for OCR processing
2020-04-14T02:47:27 ERROR: Caught ImportError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/base_task.py", line 159, in __getitem__
    item = self.chosen_dataset[idx]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/base_dataset.py", line 76, in __getitem__
    sample = self.get_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 95, in get_item
    return self.load_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 129, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 144, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 156, in __call__
    return self.processor(item, *args, **kwargs)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 493, in __call__
    self._try_download()
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 408, in _try_download
    self._load_fasttext_model(model_file)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 460, in _load_fasttext_model
    from fastText import load_model
ImportError: cannot import name 'load_model'

Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/content/drive/My Drive/mt/pythia/pythia/trainers/base_trainer.py", line 228, in train
    for batch in self.train_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ImportError: Caught ImportError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/base_task.py", line 159, in __getitem__
    item = self.chosen_dataset[idx]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/base_dataset.py", line 76, in __getitem__
    sample = self.get_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 95, in get_item
    return self.load_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 129, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 144, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 156, in __call__
    return self.processor(item, *args, **kwargs)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 493, in __call__
    self._try_download()
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 408, in _try_download
    self._load_fasttext_model(model_file)
  File "/content/drive/My Drive/mt/pythia/pythia/tasks/processors.py", line 460, in _load_fasttext_model
    from fastText import load_model
ImportError: cannot import name 'load_model'

**Comment by apsdehal** [comment]
This should be fixed in latest master.
