### ISSUE TITLE
The error happened during training or evaluating

### ISSUE THREAD

**Issue by JayZhu0104** [facebookresearch/mmf#236]
## ❓ Questions and     @@@@Help
   @ronghanghu Hi, I meet a error when I use this command lines:
`python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/m4c_textvqa/m4c.yml \
--save_dir save/m4c \
--run_type val \
--resume_file data/models/m4c_textvqa_m4c.ckpt`
And the error occurred after loading fasttext model, it says: 'NoneType' object is not callable.

The details of error as follow:
2020-04-23T22:01:08 INFO: Loading datasets
2020-04-23T22:01:09 INFO: Fetching fastText model for OCR processing
2020-04-23T22:01:09 INFO: Loading fasttext model now from /data/zhujj/projects/pythia/pythia/.vector_cache/wiki.en.bin

2020-04-23T22:01:17 INFO: Finished loading fasttext model
2020-04-23T22:01:20 **ERROR: 'NoneType' object is not callable**
Traceback (most recent call last):
  File "tools/run.py", line 86, in <module>
    run()
  File "tools/run.py", line 74, in run
    trainer.load()
  File "/data/zhujj/projects/pythia/pythia/trainers/base_trainer.py", line 46, in load
    self.load_task()
  File "/data/zhujj/projects/pythia/pythia/trainers/base_trainer.py", line 75, in load_task
    self.dataset_loader.load_datasets()
  File "/data/zhujj/projects/pythia/pythia/common/dataset_loader.py", line 23, in load_datasets
    self.train_dataset.load(**self.config)
  File "/data/zhujj/projects/pythia/pythia/datasets/multi_dataset.py", line 81, in load
    dataset_instance = builder_instance.load(self._dataset_type, attributes)
  File "/data/zhujj/projects/pythia/pythia/datasets/base_dataset_builder.py", line 70, in load
    dataset.init_processors()
  File "/data/zhujj/projects/pythia/pythia/datasets/concat_dataset.py", line 35, in _call_all_datasets_func
    value = getattr(dataset, name)(*args, **kwargs)
  File "/data/zhujj/projects/pythia/pythia/datasets/base_dataset.py", line 58, in init_processors
    processor_object = Processor(processor_params, **extra_params)
  File "/data/zhujj/projects/pythia/pythia/datasets/processors.py", line 151, in __init__
    self.processor = processor_class(params, *args, **kwargs)
TypeError: 'NoneType' object is not callable

Can you tell me what's wrong and how to solve it?Thanks!

**Comment by ronghanghu** [comment]
Hi @JayZhu0104, are you using the `master` branch or the `project/m4c` branch? The instructions (in https://github.com/facebookresearch/mmf/blob/project/m4c/projects/M4C/README.md) are for the `project/m4c` branch.

For the master branch, you can run as follows:
```
python -u tools/run.py config="projects/m4c/configs/textvqa/defaults.yaml" model=m4c dataset=textvqa training.run_type=val training.resume_file=/checkpoint/ronghanghu/pythia/data/m4c_release_models_upgraded/m4c_textvqa/m4c_textvqa_m4c.ckpt
```

**Comment by JayZhu0104** [comment]
> Hi @JayZhu0104, are you using the `master` branch or the `project/m4c` branch? The instructions (in https://github.com/facebookresearch/mmf/blob/project/m4c/projects/M4C/README.md) are for the `project/m4c` branch.
> 
> For the master branch, you can run as follows:
> 
> ```
> python -u tools/run.py config="projects/m4c/configs/textvqa/defaults.yaml" model=m4c dataset=textvqa training.run_type=val training.resume_file=/checkpoint/ronghanghu/pythia/data/m4c_release_models_upgraded/m4c_textvqa/m4c_textvqa_m4c.ckpt
> ```
Thank you for your reply! I have solved this problem now. Maybe the fasttext model that I downloaded earlier is wrong. After I delete it, I can download it again.Thank you so much!
