### ISSUE TITLE
Quickstart command fails to load weights

### ISSUE THREAD

**Issue by mckinziebrandon** [facebookresearch/mmf#340]
## 🐛 Bug

Tried running the first command in the Quickstart tutorial on current master branch (dca3ec3040ea6e8983bb39fa7a65aca4f43be848). 

## Command

```bash
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val
```

## To Reproduce

Run the following:

```bash
conda create -n mmf python=3.7
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
conda activate mmf
cd mmf && pip install -e .
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val
```
## Expected behavior

I expected it not to crash (full console output/error message pasted at the end of this issue).

## Environment

```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.6.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    papi
```

## Additional context

Full console output:

```
Namespace(config_override=None, local_rank=None, opts=['config=projects/m4c/configs/textvqa/defaults.yaml', 'datasets=textvqa', 'model=m4c', 'run_type=train_val'])
Overriding option config to projects/m4c/configs/textvqa/defaults.yaml
Overriding option datasets to textvqa
Overriding option model to m4c
Overriding option run_type to train_val
Distributed Init (Rank 1): tcp://localhost:10254
Distributed Init (Rank 4): tcp://localhost:10254
Distributed Init (Rank 7): tcp://localhost:10254
Distributed Init (Rank 2): tcp://localhost:10254
Distributed Init (Rank 5): tcp://localhost:10254
Distributed Init (Rank 0): tcp://localhost:10254
Distributed Init (Rank 6): tcp://localhost:10254
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 6
Distributed Init (Rank 3): tcp://localhost:10254
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 3
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 1
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 4
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 7
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 2
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 5
Initialized Host 7f48bf87-5d2b-4682-a81c-abc8cef58972 as Rank 0
Using seed 18783733
Logging to: ./save/logs/train_2020-06-17T21:06:18.log
Downloading features.tar.gz: 100%|█████████| 1.12G/1.12G [00:18<00:00, 59.1MB/s]
169876453it [02:40, 1055989.08it/s]                                             
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda/envs/mmf/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "/root/anaconda/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/root/mmf/mmf_cli/run.py", line 107, in run
    nprocs=config.distributed.world_size,
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/transformers/modeling_utils.py", line 415, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 768

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/root/mmf/mmf_cli/run.py", line 54, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/root/mmf/mmf_cli/run.py", line 40, in main
    trainer.load()
  File "/root/mmf/mmf/trainers/base_trainer.py", line 60, in load
    self.load_model_and_optimizer()
  File "/root/mmf/mmf/trainers/base_trainer.py", line 112, in load_model_and_optimizer
    self.model = build_model(attributes)
  File "/root/mmf/mmf/utils/build.py", line 66, in build_model
    model.build()
  File "/root/mmf/mmf/models/m4c.py", line 38, in build
    self._build_txt_encoding()
  File "/root/mmf/mmf/models/m4c.py", line 50, in _build_txt_encoding
    "bert-base-uncased", config=self.text_bert_config
  File "/root/anaconda/envs/mmf/lib/python3.7/site-packages/transformers/modeling_utils.py", line 417, in from_pretrained
    raise OSError("Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```

**Comment by mckinziebrandon** [comment]
EDIT: whoops, I think this was a simple pathing issue. Passing the full path to the defaults file seems to have resolved it. I'm getting a different issue now that's unrelated (RAM explosion) but I'll close this and file a separate issue.

Also note that installing from source is required (the config files aren't properly setup in the PyPi version).
