### ISSUE TITLE
Optimizer attributes must have a 'type' key specifying the type of optimizer.

### ISSUE THREAD

**Issue by adjgiulio** [facebookresearch/mmf#369]
Error below:

(gpu) C:\Users\giuliano\mmf>mmf_run config=projects/hateful_memes/configs/mmbt/defaults.yaml model=mmbt dataset=hateful_memes run_type=train_val
2020-06-29 11:54:39.524061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Namespace(config_override=None, local_rank=None, opts=['config=projects/hateful_memes/configs/mmbt/defaults.yaml', 'model=mmbt', 'dataset=hateful_memes', 'run_type=train_val'])
C:\Users\giuliano\anaconda3\envs\gpu\lib\site-packages\omegaconf\dictconfig.py:252: UserWarning: Keys with dot (../../../mmbt/configs/hateful_memes/defaults.yaml) are deprecated and will have different semantic meaning the next major version of OmegaConf (2.1)
See the compact keys issue for more details: https://github.com/omry/omegaconf/issues/152
You can disable this warning by setting the environment variable OC_DISABLE_DOT_ACCESS_WARNING=1
  warnings.warn(message=msg, category=UserWarning)
Overriding option config to projects/hateful_memes/configs/mmbt/defaults.yaml
Overriding option model to mmbt
Overriding option datasets to hateful_memes
Overriding option run_type to train_val
Using seed 43250716
Logging to: ./save\logs\train_2020_06_29T11_54_43.log
Traceback (most recent call last):
  File "C:\Users\giuliano\anaconda3\envs\gpu\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "c:\users\giuliano\mmf\mmf_cli\run.py", line 111, in run
    main(configuration, predict=predict)
  File "c:\users\giuliano\mmf\mmf_cli\run.py", line 40, in main
    trainer.load()
  File "c:\users\giuliano\mmf\mmf\trainers\base_trainer.py", line 60, in load
    self.load_model_and_optimizer()
  File "c:\users\giuliano\mmf\mmf\trainers\base_trainer.py", line 123, in load_model_and_optimizer
    self.optimizer = build_optimizer(self.model, self.config)
  File "c:\users\giuliano\mmf\mmf\utils\build.py", line 187, in build_optimizer
    "Optimizer attributes must have a 'type' key "
ValueError: Optimizer attributes must have a 'type' key specifying the type of optimizer. (Custom or PyTorch)

**Comment by apsdehal** [comment]
This is similar to https://github.com/facebookresearch/mmf/issues/295 . Can you try the solution provided there? 
`git clone --config core.symlinks=true https://github.com/facebookresearch/mmf.git`
