### ISSUE TITLE
An error about distributed training when training M4C.

### ISSUE THREAD

**Issue by lixiangpengcs** [facebookresearch/mmf#376]
## ❓ Questions and Help
I encounter an error when using multi-GPU: mmf_run dataset=textvqa model=m4c config=projects/m4c/configs/textvqa/defaults.yaml env.save_dir=./save/m4c
The running env is installed as suggested: torch=1.5.0, torchvision=0.6.0. 

error log:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lixiangpeng/mmf/mmf_cli/run.py", line 9, in <module>
    from mmf.common.registry import registry
  File "/home/lixiangpeng/mmf/mmf/__init__.py", line 5, in <module>
    from mmf import utils, common, modules, datasets, models
  File "/home/lixiangpeng/mmf/mmf/common/__init__.py", line 3, in <module>
    from .registry import registry
  File "/home/lixiangpeng/mmf/mmf/common/registry.py", line 409, in <module>
    setup_imports()
  File "/home/lixiangpeng/mmf/mmf/utils/env.py", line 137, in setup_imports
    importlib.import_module(module)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lixiangpeng/mmf/mmf/datasets/__init__.py", line 7, in <module>
    from .multi_dataset_loader import MultiDatasetLoader
  File "/home/lixiangpeng/mmf/mmf/datasets/multi_dataset_loader.py", line 12, in <module>
    from mmf.utils.build import build_dataloader_and_sampler, build_dataset
  File "/home/lixiangpeng/mmf/mmf/utils/build.py", line 10, in <module>
    from mmf.common import typings as mmf_typings
  File "/home/lixiangpeng/mmf/mmf/common/typings.py", line 10, in <module>
    from mmf.datasets.processors.processors import Processor
  File "/home/lixiangpeng/mmf/mmf/datasets/processors/__init__.py", line 3, in <module>
    from mmf.datasets.processors.bert_processors import MaskedTokenProcessor
  File "/home/lixiangpeng/mmf/mmf/datasets/processors/bert_processors.py", line 6, in <module>
    from transformers.tokenization_auto import AutoTokenizer
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/transformers/__init__.py", line 42, in <module>
    from .tokenization_auto import AutoTokenizer
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/transformers/tokenization_auto.py", line 24, in <module>
    from .tokenization_gpt2 import GPT2Tokenizer
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 23, in <module>
    import regex as re
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/regex/regex.py", line 403, in <module>
    import regex._regex_core as _regex_core
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: /home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/regex/_regex.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object
Traceback (most recent call last):
  File "run.py", line 115, in <module>
    run()
  File "run.py", line 107, in run
    nprocs=config.distributed.world_size,
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/lixiangpeng/mmf/mmf_cli/run.py", line 54, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/lixiangpeng/mmf/mmf_cli/run.py", line 44, in main
    trainer.train()
  File "/home/lixiangpeng/mmf/mmf/trainers/base_trainer.py", line 253, in train
    should_break = self._logistics(report)
  File "/home/lixiangpeng/mmf/mmf/trainers/base_trainer.py", line 387, in _logistics
    should_break = self._try_full_validation()
  File "/home/lixiangpeng/mmf/mmf/trainers/base_trainer.py", line 406, in _try_full_validation
    report, meter = self.evaluate(self.val_loader)
  File "/home/lixiangpeng/mmf/mmf/trainers/base_trainer.py", line 443, in evaluate
    for batch in tqdm(loader, disable=disable_tqdm):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 67668) is killed by signal: Killed. 

(base) lixiangpeng@dgx-2:~/mmf/mmf_cli$ /home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))

the training log is as:
2020-07-01T15:47:52 | INFO | mmf.train : Loading datasets
2020-07-01T15:48:51 | INFO | mmf.train : CUDA Device 0 is: Tesla V100-SXM2-32GB
2020-07-01T15:48:52 | INFO | mmf.train : Torch version is: 1.5.0
2020-07-01T15:48:52 | WARNING | py.warnings : /home/lixiangpeng/mmf/mmf/utils/distributed.py:273: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  builtin_warn(*args, **kwargs)

2020-07-01T15:48:52 | WARNING | py.warnings : /home/lixiangpeng/mmf/mmf/utils/distributed.py:273: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  builtin_warn(*args, **kwargs)

2020-07-01T15:48:52 | INFO | mmf.train : ===== Model =====
2020-07-01T15:48:52 | INFO | mmf.train : DistributedDataParallel(
  (module): M4C(

2020-07-01T15:48:52 | INFO | mmf.train : Total Parameters: 90850184. Trained Parameters: 90850184
2020-07-01T15:48:52 | INFO | mmf.train : Starting training...
2020-07-01T15:50:15 | WARNING | py.warnings : /home/lixiangpeng/mmf/mmf/utils/distributed.py:273: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  builtin_warn(*args, **kwargs)

2020-07-01T15:51:34 | INFO | mmf.train : progress: 100/24000, train/total_loss: 727.5215, train/total_loss/avg: 727.5215, train/textvqa/m4c_decoding_bce_with_mask: 727.5215, train/textvqa/m4c_decoding_bce_with_mask/avg: 727.5215, max mem: 3241.0, experiment: run, epoch: 1, num_updates: 100, iterations: 100, max_updates: 24000, lr: 0.00003, ups: 0.62, time: 02m 42s 098ms, time_since_start: 03m 41s 540ms, eta: 10h 46m 59s 118ms
2020-07-01T15:52:56 | INFO | mmf.train : progress: 200/24000, train/total_loss: 67.8769, train/total_loss/avg: 397.6992, train/textvqa/m4c_decoding_bce_with_mask: 67.8769, train/textvqa/m4c_decoding_bce_with_mask/avg: 397.6992, max mem: 3241.0, experiment: run, epoch: 1, num_updates: 200, iterations: 200, max_updates: 24000, lr: 0.00004, ups: 1.22, time: 01m 22s 081ms, time_since_start: 05m 03s 622ms, eta: 05h 26m 14s 429ms
2020-07-01T15:55:56 | INFO | mmf.train : progress: 300/24000, train/total_loss: 67.8769, train/total_loss/avg: 268.8288, train/textvqa/m4c_decoding_bce_with_mask: 67.8769, train/textvqa/m4c_decoding_bce_with_mask/avg: 268.8288, max mem: 3241.0, experiment: run, epoch: 9, num_updates: 300, iterations: 300, max_updates: 24000, lr: 0.00004, ups: 0.56, time: 03m 047ms, time_since_start: 08m 03s 669ms, eta: 11h 52m 36s 631ms
2020-07-01T15:57:18 | INFO | mmf.train : progress: 400/24000, train/total_loss: 11.0879, train/total_loss/avg: 203.5260, train/textvqa/m4c_decoding_bce_with_mask: 11.0879, train/textvqa/m4c_decoding_bce_with_mask/avg: 203.5260, max mem: 3241.0, experiment: run, epoch: 9, num_updates: 400, iterations: 400, max_updates: 24000, lr: 0.00005, ups: 1.23, time: 01m 21s 869ms, time_since_start: 09m 25s 539ms, eta: 05h 22m 39s 971ms
2020-07-01T15:58:41 | INFO | mmf.train : progress: 500/24000, train/total_loss: 11.0879, train/total_loss/avg: 164.0767, train/textvqa/m4c_decoding_bce_with_mask: 11.0879, train/textvqa/m4c_decoding_bce_with_mask/avg: 164.0767, max mem: 3241.0, experiment: run, epoch: 9, num_updates: 500, iterations: 500, max_updates: 24000, lr: 0.00006, ups: 1.20, time: 01m 23s 367ms, time_since_start: 10m 48s 907ms, eta: 05h 27m 10s 517ms
2020-07-01T16:01:32 | INFO | mmf.train : progress: 600/24000, train/total_loss: 7.6178, train/total_loss/avg: 137.7341, train/textvqa/m4c_decoding_bce_with_mask: 7.6178, train/textvqa/m4c_decoding_bce_with_mask/avg: 137.7341, max mem: 3241.0, experiment: run, epoch: 17, num_updates: 600, iterations: 600, max_updates: 24000, lr: 0.00007, ups: 0.59, time: 02m 50s 826ms, time_since_start: 13m 39s 734ms, eta: 11h 07m 33s 378ms
2020-07-01T16:02:56 | INFO | mmf.train : progress: 700/24000, train/total_loss: 7.6178, train/total_loss/avg: 118.9084, train/textvqa/m4c_decoding_bce_with_mask: 7.6178, train/textvqa/m4c_decoding_bce_with_mask/avg: 118.9084, max mem: 3241.0, experiment: run, epoch: 17, num_updates: 700, iterations: 700, max_updates: 24000, lr: 0.00008, ups: 1.20, time: 01m 23s 860ms, time_since_start: 15m 03s 594ms, eta: 05h 26m 18s 603ms
2020-07-01T16:04:22 | INFO | mmf.train : progress: 800/24000, train/total_loss: 6.2794, train/total_loss/avg: 104.6841, train/textvqa/m4c_decoding_bce_with_mask: 6.2794, train/textvqa/m4c_decoding_bce_with_mask/avg: 104.6841, max mem: 3241.0, experiment: run, epoch: 17, num_updates: 800, iterations: 800, max_updates: 24000, lr: 0.00008, ups: 1.18, time: 01m 25s 870ms, time_since_start: 16m 29s 465ms, eta: 05h 32m 41s 897ms
2020-07-01T16:07:15 | INFO | mmf.train : progress: 900/24000, train/total_loss: 6.2794, train/total_loss/avg: 93.7110, train/textvqa/m4c_decoding_bce_with_mask: 6.2794, train/textvqa/m4c_decoding_bce_with_mask/avg: 93.7110, max mem: 3241.0, experiment: run, epoch: 25, num_updates: 900, iterations: 900, max_updates: 24000, lr: 0.00009, ups: 0.58, time: 02m 52s 588ms, time_since_start: 19m 22s 053ms, eta: 11h 05m 47s 596ms
2020-07-01T16:08:35 | INFO | mmf.train : progress: 1000/24000, train/total_loss: 6.0210, train/total_loss/avg: 84.8744, train/textvqa/m4c_decoding_bce_with_mask: 6.0210, train/textvqa/m4c_decoding_bce_with_mask/avg: 84.8744, max mem: 3241.0, experiment: run, epoch: 25, num_updates: 1000, iterations: 1000, max_updates: 24000, lr: 0.0001, ups: 1.25, time: 01m 20s 676ms, time_since_start: 20m 42s 730ms, eta: 05h 09m 52s 717ms
2020-07-01T16:08:35 | INFO | mmf.train : Checkpoint time. Saving a checkpoint.
2020-07-01T16:08:54 | INFO | mmf.train : Evaluation time. Running on full validation set...

When I disable distributed related code or set num_workers equals 0, this error disappears. However, the running speed becomes real slow. I want to know why?

**Comment by apsdehal** [comment]
This is probably related to #374 and #355. Let us know if this fixes it after it lands.

**Comment by lixiangpengcs** [comment]
I am sorry that I can't figure out that means. Could you give me some specific suggestions to solve this problem?

**Comment by apsdehal** [comment]
Apologies if that wasn't clear. The fix in #374 is on the way to land in master which might be causing this issue. It should land within an hour. `git pull origin master` when that is done and retest if the issue still persists. Let me know if it still doesn't make sense.

**Comment by apsdehal** [comment]
Actually never mind, looking at it more closely, this seems something else. Investigating.

**Comment by lixiangpengcs** [comment]
I have updated the stack trace and training log. Thanks a lot.

**Comment by apsdehal** [comment]
@lixiangpengcs Can you try on master, and let me know if it fixes it or not?

**Comment by lixiangpengcs** [comment]
Hello， I re-run the mmf and it still raise the error. And this error maybe is caused by spawn module:

Traceback (most recent call last):
  File "run.py", line 115, in <module>
    run()
  File "run.py", line 107, in run
    nprocs=config.distributed.world_size,
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/lixiangpeng/mmf/mmf_cli/run.py", line 54, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/lixiangpeng/mmf/mmf_cli/run.py", line 44, in main
    trainer.train()
  File "/home/lixiangpeng/mmf/mmf/trainers/mmf_trainer.py", line 104, in train
    self.training_loop()
  File "/home/lixiangpeng/mmf/mmf/trainers/core/training_loop.py", line 34, in training_loop
    self.run_training_epoch()
  File "/home/lixiangpeng/mmf/mmf/trainers/core/training_loop.py", line 84, in run_training_epoch
    report, meter = self.evaluation_loop(self.val_loader)
  File "/home/lixiangpeng/mmf/mmf/trainers/core/evaluation_loop.py", line 25, in evaluation_loop
    for batch in tqdm.tqdm(loader, disable=disable_tqdm):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
MemoryError: Caught MemoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    report, meter = self.evaluation_loop(self.val_loader)
  File "/home/lixiangpeng/mmf/mmf/trainers/core/evaluation_loop.py", line 25, in evaluation_loop
    for batch in tqdm.tqdm(loader, disable=disable_tqdm):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
MemoryError: Caught MemoryError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/lixiangpeng/mmf/mmf/datasets/builders/textvqa/dataset.py", line 90, in __getitem__
    current_sample = self.add_sample_details(sample_info, current_sample)
  File "/home/lixiangpeng/mmf/mmf/datasets/builders/textvqa/dataset.py", line 161, in add_sample_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/home/lixiangpeng/mmf/mmf/datasets/processors/processors.py", line 153, in __call__
    return self.processor(item, *args, **kwargs)
  File "/home/lixiangpeng/mmf/mmf/datasets/processors/processors.py", line 482, in __call__
    self._load_fasttext_model(self.model_file)
  File "/home/lixiangpeng/mmf/mmf/datasets/processors/processors.py", line 459, in _load_fasttext_model
    self.model = load_model(model_file)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/fasttext/FastText.py", line 350, in load_model
    return _FastText(model_path=path)
  File "/home/lixiangpeng/env/anaconda/lib/python3.7/site-packages/fasttext/FastText.py", line 43, in __init__
    self.f.loadModel(model_path)
MemoryError: std::bad_alloc


(base) lixiangpeng@dgx-2:~/mmf/mmf_cli$ /home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))
/home/lixiangpeng/env/anaconda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 41 leaked semaphores to clean up at shutdown
  len(cache))

The training log is:
2020-07-03T10:22:52 | INFO | mmf.train : Total Parameters: 90850184. Trained Parameters: 90850184
2020-07-03T10:22:52 | INFO | mmf.train : Starting training...
2020-07-03T10:25:49 | INFO | mmf.train : progress: 100/24000, train/total_loss: 718.9424, train/total_loss/avg: 718.9424, train/textvqa/m4c_decoding_bce_with_mask: 718.9424, train/textvqa/m4c_decoding_bce_with_mask/avg: 718.9424, max mem: 3239.0, experiment: run, epoch: 1, num_updates: 100, iterations: 100, max_updates: 24000, lr: 0.00003, ups: 0.56, time: 02m 57s 079ms, time_since_start: 02m 57s 142ms, eta: 11h 46m 46s 572ms
2020-07-03T10:27:13 | INFO | mmf.train : progress: 200/24000, train/total_loss: 66.9629, train/total_loss/avg: 392.9527, train/textvqa/m4c_decoding_bce_with_mask: 66.9629, train/textvqa/m4c_decoding_bce_with_mask/avg: 392.9527, max mem: 3239.0, experiment: run, epoch: 1, num_updates: 200, iterations: 200, max_updates: 24000, lr: 0.00004, ups: 1.20, time: 01m 23s 825ms, time_since_start: 04m 20s 967ms, eta: 05h 33m 10s 317ms
2020-07-03T10:30:25 | INFO | mmf.train : progress: 300/24000, train/total_loss: 66.9629, train/total_loss/avg: 265.6916, train/textvqa/m4c_decoding_bce_with_mask: 66.9629, train/textvqa/m4c_decoding_bce_with_mask/avg: 265.6916, max mem: 3239.0, experiment: run, epoch: 9, num_updates: 300, iterations: 300, max_updates: 24000, lr: 0.00004, ups: 0.52, time: 03m 11s 467ms, time_since_start: 07m 32s 434ms, eta: 12h 37m 48s 454ms
2020-07-03T10:31:50 | INFO | mmf.train : progress: 400/24000, train/total_loss: 11.1694, train/total_loss/avg: 201.1575, train/textvqa/m4c_decoding_bce_with_mask: 11.1694, train/textvqa/m4c_decoding_bce_with_mask/avg: 201.1575, max mem: 3239.0, experiment: run, epoch: 9, num_updates: 400, iterations: 400, max_updates: 24000, lr: 0.00005, ups: 1.18, time: 01m 25s 262ms, time_since_start: 08m 57s 697ms, eta: 05h 36m 02s 168ms
2020-07-03T10:33:13 | INFO | mmf.train : progress: 500/24000, train/total_loss: 11.1694, train/total_loss/avg: 162.2108, train/textvqa/m4c_decoding_bce_with_mask: 11.1694, train/textvqa/m4c_decoding_bce_with_mask/avg: 162.2108, max mem: 3239.0, experiment: run, epoch: 9, num_updates: 500, iterations: 500, max_updates: 24000, lr: 0.00006, ups: 1.20, time: 01m 23s 309ms, time_since_start: 10m 21s 006ms, eta: 05h 26m 56s 940ms
2020-07-03T10:36:20 | INFO | mmf.train : progress: 600/24000, train/total_loss: 7.5554, train/total_loss/avg: 136.1825, train/textvqa/m4c_decoding_bce_with_mask: 7.5554, train/textvqa/m4c_decoding_bce_with_mask/avg: 136.1825, max mem: 3239.0, experiment: run, epoch: 17, num_updates: 600, iterations: 600, max_updates: 24000, lr: 0.00007, ups: 0.54, time: 03m 06s 791ms, time_since_start: 13m 27s 798ms, eta: 12h 09m 56s 606ms
2020-07-03T10:37:45 | INFO | mmf.train : progress: 700/24000, train/total_loss: 7.5554, train/total_loss/avg: 117.5738, train/textvqa/m4c_decoding_bce_with_mask: 7.5554, train/textvqa/m4c_decoding_bce_with_mask/avg: 117.5738, max mem: 3239.0, experiment: run, epoch: 17, num_updates: 700, iterations: 700, max_updates: 24000, lr: 0.00008, ups: 1.19, time: 01m 24s 626ms, time_since_start: 14m 52s 424ms, eta: 05h 29m 17s 353ms
2020-07-03T10:39:08 | INFO | mmf.train : progress: 800/24000, train/total_loss: 6.4236, train/total_loss/avg: 103.5454, train/textvqa/m4c_decoding_bce_with_mask: 6.4236, train/textvqa/m4c_decoding_bce_with_mask/avg: 103.5454, max mem: 3239.0, experiment: run, epoch: 17, num_updates: 800, iterations: 800, max_updates: 24000, lr: 0.00008, ups: 1.20, time: 01m 23s 362ms, time_since_start: 16m 15s 787ms, eta: 05h 22m 58s 778ms
2020-07-03T10:42:21 | INFO | mmf.train : progress: 900/24000, train/total_loss: 6.4236, train/total_loss/avg: 92.6796, train/textvqa/m4c_decoding_bce_with_mask: 6.4236, train/textvqa/m4c_decoding_bce_with_mask/avg: 92.6796, max mem: 3239.0, experiment: run, epoch: 25, num_updates: 900, iterations: 900, max_updates: 24000, lr: 0.00009, ups: 0.52, time: 03m 13s 033ms, time_since_start: 19m 28s 821ms, eta: 12h 24m 40s 048ms
2020-07-03T10:43:46 | INFO | mmf.train : Checkpoint time. Saving a checkpoint.
2020-07-03T10:44:02 | INFO | mmf.train : progress: 1000/24000, train/total_loss: 6.0410, train/total_loss/avg: 83.9503, train/textvqa/m4c_decoding_bce_with_mask: 6.0410, train/textvqa/m4c_decoding_bce_with_mask/avg: 83.9503, max mem: 3239.0, experiment: run, epoch: 25, num_updates: 1000, iterations: 1000, max_updates: 24000, lr: 0.0001, ups: 0.99, time: 01m 41s 537ms, time_since_start: 21m 10s 359ms, eta: 06h 30m 433ms
2020-07-03T10:44:02 | INFO | mmf.train : Evaluation time. Running on full validation set...

**Comment by apsdehal** [comment]
Thanks for the updated stack trace. The error is much more clear now:
> MemoryError: Caught MemoryError in DataLoader worker process 0.
Can you trying lowering your num_workers to 2 by adding `training.num_workers=2`. If this still doesn't work, trying lowering it further to 1. Let us know if that works.

**Comment by lixiangpengcs** [comment]
It is so strange that it runs normally when training.num_workers=2. But it is obviously slower than when num_workers=4.
