### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by rrlcs** [facebookresearch/mmf#409]
## ❓ Questions and Help
I was trying to evaluate the pre-trained model. But encountered the following error. Can you help me with this?

**mmf_run config=projects/hateful_memes/configs/unimodal/image.yaml model=unimodal_image dataset=hateful_memes run_type=val checkpoint.resume_zoo=unimodal_image.hateful_memes.images**

Namespace(config_override=None, local_rank=None, opts=['config=projects/hateful_memes/configs/unimodal/image.yaml', 'model=unimodal_image', 'dataset=hateful_memes', 'run_type=val', 'checkpoint.resume_zoo=unimodal_image.hateful_memes.images'])
Overriding option config to projects/hateful_memes/configs/unimodal/image.yaml
Overriding option model to unimodal_image
Overriding option datasets to hateful_memes
Overriding option run_type to val
Overriding option checkpoint.resume_zoo to unimodal_image.hateful_memes.images
Using seed 59269590
Logging to: ./save/logs/train_2020-07-16T01:12:59.log
  0%|                                                                                                                          | 0/15 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home2/raviraja/.local/bin/mmf_run", line 11, in <module>
    sys.exit(run())
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf_cli/run.py", line 111, in run
    main(configuration, predict=predict)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf_cli/run.py", line 44, in main
    trainer.train()
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 216, in train
    self.inference()
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 486, in inference
    self._inference_run("val")
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 499, in _inference_run
    getattr(self, f"{dataset_type}_loader"), use_tqdm=True
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 444, in evaluate
    report = self._forward_pass(batch)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 274, in _forward_pass
    model_output = self.model(prepared_batch)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/models/base_model.py", line 148, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/models/unimodal.py", line 102, in forward
    embedding = self.base(modal, *args)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/models/unimodal.py", line 31, in forward
    x = self.encoder(x, *args, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/mmf/modules/encoders.py", line 130, in forward
    out = self.pool(self.model(x))
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home2/raviraja/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 1061, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**torch==1.5.0+cu101 torchvision==0.6.0+cu101**

**Comment by vedanuj** [comment]
Hi @rrlcs 

Can you follow the Bugs Issue template and paste the output of `python -m torch.utils.collect_env` ?

**Comment by rrlcs** [comment]
> Hi @rrlcs
> 
> Can you follow the Bugs Issue template and paste the output of `python -m torch.utils.collect_env` ?

Here I'm pasting the terminal output for **python -m torch.utils.collect_env**

Collecting environment information...
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.5.0+cu101
[pip3] torch-geometric==1.6.0
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.6
[pip3] torchtext==0.5.0
[pip3] torchvision==0.6.0+cu101
[conda] Could not collect

**Comment by vedanuj** [comment]
This is usually a problem with your CUDA driver and related to pytorch specifically rather than mmf. 
Tesla K40C issue here : https://github.com/pytorch/pytorch/issues/31285#issuecomment-579089919

You might have to build pytorch from source. Closing as this is not related to MMF. Please reopen if you think otherwise.

**Comment by rrlcs** [comment]
> This is usually a problem with your CUDA driver and related to pytorch specifically rather than mmf.
> Tesla K40C issue here : [pytorch/pytorch#31285 (comment)](https://github.com/pytorch/pytorch/issues/31285#issuecomment-579089919)
> 
> You might have to build pytorch from source. Closing as this is not related to MMF. Please reopen if you think otherwise.

Hi @vedanuj 
Thanks for the link. That helped.
