### ISSUE TITLE
KeyError: 'captions'

### ISSUE THREAD

**Issue by mokadyr** [facebookresearch/mmf#482]
## 🐛 Bug

`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/private/home/mokady/mokady_intern2/mmf/mmf/common/report.py", line 70, in __getattr__
    return self[key]
KeyError: 'captions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/private/home/mokady/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/private/home/mokady/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/private/home/mokady/mmf/mmf/trainers/mmf_trainer.py", line 104, in train
    self.inference()
  File "/private/home/mokady/mmf/mmf/trainers/mmf_trainer.py", line 123, in inference
    self.prediction_loop(dataset)
  File "/private/home/mokady/mmf/mmf/trainers/core/evaluation_loop.py", line 67, in prediction_loop
    reporter.add_to_report(report, self.model)
  File "/private/home/mokady/mmf/mmf/common/test_reporter.py", line 154, in add_to_report
    results = self.current_dataset.format_for_prediction(report)
  File "/private/home/mokady/mmf/mmf/datasets/concat_dataset.py", line 35, in _call_all_datasets_func
    value = getattr(dataset, name)(*args, **kwargs)
  File "/private/home/mokady/mmf/mmf/datasets/builders/coco/dataset.py", line 63, in format_for_prediction
    captions = report.captions.tolist()
  File "/private/home/mokady/mmf/mmf/common/report.py", line 72, in __getattr__
    raise AttributeError(key)
AttributeError: captions`

## Command

`mmf_run config=projects/butd/configs/coco/defaults.yaml run_type=val dataset=coco model=butd checkpoint.resume_file=./save/models/model_50000.ckpt evaluation.predict=true`

## To Reproduce

1. Train:
`mmf_run config=projects/butd/configs/coco/defaults.yaml run_type=train_val dataset=coco model=butd`

2. Predict:
`mmf_run config=projects/butd/configs/coco/defaults.yaml run_type=val dataset=coco model=butd checkpoint.resume_file=./save/models/model_50000.ckpt evaluation.predict=true`

3.

**Comment by apsdehal** [comment]
Thanks for reporting this issue. We will take a look and get back to you.

**Comment by apsdehal** [comment]
Fix is to use beam_search configuration:
```
mmf_run config=projects/butd/configs/coco/beam_search.yaml run_type=val dataset=coco model=butd checkpoint.resume_file=./save/models/model_50000.ckpt evaluation.predict=true
```
We should update the documentation to cover this.
