### ISSUE TITLE
pretraining VisualBERT on COCO

### ISSUE THREAD

**Issue by rizavelioglu** [facebookresearch/mmf#539]
## ❓ Questions and Help

---
How one can pretrain **VisualBERT** (`bert-large-uncased`) on **COCO** dataset?

---

I've tried the following but no avail:

- I changed the [Line#155](https://github.com/facebookresearch/mmf/blob/24dedb1908333782de3a0ee54253b229c9a7218d/mmf/models/visual_bert.py#L155) in `mmf/models/visual_bert.py` and set `bert_config` to the following config ([as described in comments](https://github.com/facebookresearch/mmf/blob/24dedb1908333782de3a0ee54253b229c9a7218d/mmf/models/visual_bert.py#L151)), which is the config of `bert-large-uncased`:

```
self.bert_config = BertConfig.from_dict({"attention_probs_dropout_prob":0.1,
                                                "hidden_act":"gelu",
                                                "hidden_dropout_prob":0.1,
                                                "hidden_size":1024,
                                                "initializer_range":0.02,
                                                "intermediate_size":4096,
                                                "layer_norm_eps":1e-12,
                                                "max_position_embeddings":512,
                                                "model_type":"bert",
                                                "num_attention_heads":16,
                                                "num_hidden_layers":24,
                                                "pad_token_id":0,
                                                "type_vocab_size":2,
                                                "vocab_size":30522})
```

- Then, one can run:

```
mmf_run config="projects/visual_bert/configs/masked_coco/pretrain_train_val.yaml" \
        model="visual_bert" \
        dataset=coco \
        run_type=train \
        model_config.visual_bert.bert_model_name=None \
        model_config.visual_bert.training_head_type="pretraining" \
```

which gives the following error:

<details>
<summary><b><i>Click to see the error</i></b></summary>

> Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/riza/mmf/mmf_cli/run.py", line 115, in run
    torch.multiprocessing.spawn(
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/riza/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/riza/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/riza/mmf/mmf/trainers/mmf_trainer.py", line 108, in train
    self.training_loop()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 36, in training_loop
    self.run_training_epoch()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 72, in run_training_epoch
    self.run_training_batch(batch)
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 110, in run_training_batch
    report = self._forward(batch)
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 129, in _forward
    model_output = self.model(prepared_batch)
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 445, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/riza/mmf/mmf/models/base_model.py", line 147, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/riza/mmf/mmf/models/visual_bert.py", line 560, in forward
    sample_list = self.update_sample_list_based_on_head(sample_list)
  File "/home/riza/mmf/mmf/models/visual_bert.py", line 489, in update_sample_list_based_on_head
    bert_input_ids = sample_list.input_ids
  File "/home/riza/mmf/mmf/common/sample.py", line 163, in __getattr__
    raise AttributeError(
AttributeError: Key input_ids not found in the SampleList. Valid choices are ['text', 'caption_id', 'caption_len', 'image_id', 'image_feature_0', 'answers', 'dataset_name', 'dataset_type']

</details>

**Comment by apsdehal** [comment]
Hi, You want the dataset selected as `masked_coco` instead of `coco`. Also, I think instead of manually replacing in the code have you tried setting:

```
model_config.visual_bert.bert_model_name=bert-large-uncased
```

**Comment by rizavelioglu** [comment]
Hey, thanks for the answer! Tried the following command:

```
mmf_run config="/home/riza/mmf/projects/visual_bert/configs/masked_coco/pretrain_train_val.yaml" \
        model="visual_bert" \
        dataset=masked_coco \
        run_type=train_val \
        model_config.visual_bert.bert_model_name=bert-large-uncased \
        model_config.visual_bert.training_head_type="pretraining" \
```

but got the error: 

> RuntimeError: /home/riza/.cache/torch/mmf/data/datasets/coco/defaults/features/coco_trainval2014.lmdb path specified for LMDB features doesn't exists.

---

Since I selected dataset as `coco` beforehand I downloaded `trainval2014.tar.gz` and `test2015.tar.gz` into the folder ` /home/riza/.cache/torch/mmf/data/datasets/coco/defaults/features`. 

But, as the code points out, there's no file named `coco_trainval2014.lmdb`. Is that just a typo in the code?

**Comment by apsdehal** [comment]
Yup, those needs to trainval2014.lmdb only. Can you open up a PR to fix that?

**Comment by rizavelioglu** [comment]
Sure thing 👍 Will do the changes and open up a PR in a minute

**Comment by rizavelioglu** [comment]
Trying to pretrain VisualBERT (bert-large-uncased) on COCO dataset and running the code:

```
mmf_run config="/home/riza/mmf/projects/visual_bert/configs/masked_coco/pretrain_train_val.yaml" \
        model="visual_bert" \
        dataset=masked_coco \
        run_type=train_val \
        training.batch_size=8 \
	training.max_epochs=10 \
        model_config.visual_bert.bert_model_name=bert-large-uncased \
        model_config.visual_bert.training_head_type="pretraining" \
        dataset_config.masked_coco.processors.masked_token_processor.params.tokenizer_config.type=bert-large-uncased \
```

raises the following error:

> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).


<details>
<summary><b><i>See the full output</i></b></summary>

Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/riza/mmf/mmf_cli/run.py", line 115, in run
    torch.multiprocessing.spawn(
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/riza/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/riza/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/riza/mmf/mmf/trainers/mmf_trainer.py", line 108, in train
    self.training_loop()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 36, in training_loop
    self.run_training_epoch()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 72, in run_training_epoch
    self.run_training_batch(batch)
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 110, in run_training_batch
    report = self._forward(batch)
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 129, in _forward
    model_output = self.model(prepared_batch)
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 462, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

</details>

**Comment by apsdehal** [comment]
Hi @rizavelioglu,

As the error suggests, please add `training.find_unused_parameters=True` at the end of your command.

**Comment by rizavelioglu** [comment]
Hi @apsdehal,

Adding `training.find_unused_parameters=True` to the config yields:

> ValueError: cannot convert float NaN to integer

This behaviour doesn't happen when VisualBERT is fine-tuned.

<details>
<summary><b><i>See the full error</i></b></summary>

Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/riza/mmf/mmf_cli/run.py", line 115, in run
    torch.multiprocessing.spawn(
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/riza/anaconda3/envs/hateful/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/riza/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/riza/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/riza/mmf/mmf/trainers/mmf_trainer.py", line 108, in train
    self.training_loop()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 36, in training_loop
    self.run_training_epoch()
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 72, in run_training_epoch
    self.run_training_batch(batch)
  File "/home/riza/mmf/mmf/trainers/core/training_loop.py", line 123, in run_training_batch
    self.on_batch_end(report=report, meter=self.meter, should_log=should_log)
  File "/home/riza/mmf/mmf/trainers/core/callback_hook.py", line 40, in on_batch_end
    callback.on_batch_end(**kwargs)
  File "/home/riza/mmf/mmf/trainers/callbacks/logistics.py", line 77, in on_batch_end
    "eta": self._calculate_time_left(),
  File "/home/riza/mmf/mmf/trainers/callbacks/logistics.py", line 139, in _calculate_time_left
    return self.train_timer.get_time_hhmmss(gap=time_left)
  File "/home/riza/mmf/mmf/utils/timer.py", line 61, in get_time_hhmmss
    time_str = format[idx] % item + " " + time_str
ValueError: cannot convert float NaN to integer

</details>
