### ISSUE TITLE
Trying to replicate the documentation concat_bert code

### ISSUE THREAD

**Issue by s-sourav15** [facebookresearch/mmf#542]
## ❓ Questions and Help
I was trying to replicate the concat_bert code using the official documentation but during the training of the model i run into this error:
Traceback (most recent call last):
  File "/usr/local/bin/mmf_run", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/mmf_cli/run.py", line 111, in run
    main(configuration, predict=predict)
  File "/usr/local/lib/python3.6/dist-packages/mmf_cli/run.py", line 44, in main
    trainer.train()
  File "/usr/local/lib/python3.6/dist-packages/mmf/trainers/base_trainer.py", line 252, in train
    self._backward(loss)
  File "/usr/local/lib/python3.6/dist-packages/mmf/trainers/base_trainer.py", line 282, in _backward
    loss.backward()
AttributeError: 'int' object has no attribute 'backward'

could you please help me with this?

**Comment by vedanuj** [comment]
Can you provide more information about your environment and your run command?

**Comment by s-sourav15** [comment]
mmf_run config="mmf/configs/experiments/defaults.yaml"  model=concat_bert dataset=hateful_memes run_type=train_val
This is the command I use to run the code. Actually I run it on cloud (google colab).

**Comment by vedanuj** [comment]
Can you try using this notebook : https://github.com/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb and check if anything is missing in yours?

**Comment by s-sourav15** [comment]
Now I am getting this error even after installing the mmf

ImportError: cannot import name 'Logger'

**Comment by apsdehal** [comment]
This should be fixed with #585
