### ISSUE TITLE
Segmentation fault when runing extract_features_vmb.py

### ISSUE THREAD

**Issue by aggiejiang** [facebookresearch/mmf#590]
## 🐛 Bug

```
Fatal Python error: Segmentation fault

Current thread 0x00002aece2f1aec0 (most recent call first):
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 27 in boxlist_nms
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 115 in forward_for_single_feature_map
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 135 in forward
  File "/data/home/acw519/.conda/envs/rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491 in __call__
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 117 in _forward_test
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 96 in forward
  File "/data/home/acw519/.conda/envs/rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491 in __call__
  File "/data/home/acw519/github/vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52 in forward
  File "/data/home/acw519/.conda/envs/rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491 in __call__
  File "/data/EECS-SDSlab/datasets/hateful_memes_aug_dataset/features/extract_features_vmb.py", line 236 in get_detectron_features
  File "/data/EECS-SDSlab/datasets/hateful_memes_aug_dataset/features/extract_features_vmb.py", line 307 in extract_features
  File "/data/EECS-SDSlab/datasets/hateful_memes_aug_dataset/features/extract_features_vmb.py", line 318 in <module>
/opt/sge_spool/8.6.12/nxg2/job_scripts/1241251: line 20:  6048 Segmentation fault      python -Xfaulthandler /data/EECS-SDSlab/datasets/hateful_memes_aug_dataset/features/extract_features_vmb.py  --image_dir /data/EECS-SDSlab/datasets/datasets/hateful_memes/defaults/images/img/
```

## Command

```
python -Xfaulthandler /data/EECS-SDSlab/datasets/hateful_memes_aug_dataset/features/extract_features_vmb.py  --image_dir /data/EECS-SDSlab/datasets/datasets/hateful_memes/defaults/images/img/
```

I use faulthander to get a detailed traceback.

## Environment

 - PyTorch Version: 1.0.0.dev20190328
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1

Could you please give me any tip about this? Thanks!

**Comment by vedanuj** [comment]
Which version of vqa-maskrcnn-benchmark did you install? Can you also try upgrading pytorch to latest version 1.6?

**Comment by apsdehal** [comment]
I was trying to clone the vqa-maskrcnn-benchmark from scratch today and saw this error, this got fixed when I recompiled it with torch 1.6 and latest torchvision version. For brevity, here are the steps I followed:

```
- Cloned MMF
- Installed MMF in develop mode
- Made sure that I had right torch installed for the cuda version on my machine
- Installed yacs, opencv, cython
- Clone vqa-maskrcnn-benchmark
- cd into dir, and `rm -rf build`
- python setup.py build
- python setup.py develop
- Run the extraction script.
```

**Comment by aggiejiang** [comment]
It works after upgrading the torch version to 1.6.0+cu101. Thanks a lot!

**Comment by rizavelioglu** [comment]
Hi @apsdehal,
I followed the steps you provided but still no result. 

First, I ran the following bash script:
```bash
pip install torch==1.6.0 torchvision==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

git clone --config core.symlinks=true https://github.com/facebookresearch/mmf.git
cd mmf
pip install --editable .

conda install -c conda-forge opencv
pip install ninja yacs cython matplotlib

cd ..
git clone https://gitlab.com/vedanuj/vqa-maskrcnn-benchmark
cd vqa-maskrcnn-benchmark
rm -rf build
python setup.py build develop
```

<details>
<summary><b><i>Then I had the following error:</i></b></summary>

```
../lib/python3.6/site-packages/torch/cuda/__init__.py:125: UserWarning: 
GeForce RTX 2080 Ti with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 compute_37.
If you want to use the GeForce RTX 2080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
../vqa-maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py:45: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629431274/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  keep = ((ws >= min_size) & (hs >= min_size)).nonzero().squeeze(1)
Traceback (most recent call last):
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 317, in <module>
    feature_extractor.extract_features()
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 306, in extract_features
    features, infos = self.get_detectron_features(chunk)
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 235, in get_detectron_features
    output = self.detection_model(current_img_list)
  File "/home/riza/anaconda3/envs/mmf_feats/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "../anaconda3/envs/mmf_feats/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 96, in forward
    return self._forward_test(anchors, objectness, rpn_box_regression)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 117, in _forward_test
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "../anaconda3/envs/mmf_feats/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 135, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 115, in forward_for_single_feature_map
    score_field="objectness",
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: Not compiled with GPU support
```
</details>

---
Then I installed latest versions of `torch` and `torchvision` for `CUDA 10.01`:
```
pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
``` 
and re-built vqa-maskrcnn-benchmark.

<details>
<summary><b><i>But then after running the extraction script I get the following error:</i></b></summary>

```
../vqa-maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py:45: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  keep = ((ws >= min_size) & (hs >= min_size)).nonzero().squeeze(1)
Traceback (most recent call last):
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 317, in <module>
    feature_extractor.extract_features()
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 306, in extract_features
    features, infos = self.get_detectron_features(chunk)
  File "mmf/tools/scripts/features/extract_features_vmb.py", line 235, in get_detectron_features
    output = self.detection_model(current_img_list)
  File "../anaconda3/envs/mmf_feats/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "../anaconda3/envs/mmf_feats/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 96, in forward
    return self._forward_test(anchors, objectness, rpn_box_regression)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 117, in _forward_test
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "../anaconda3/envs/mmf_feats/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 135, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 111, in forward_for_single_feature_map
    boxlist = boxlist_nms(
  File "../vqa-maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 27, in boxlist_nms
    keep = _box_nms(boxes, score, nms_thresh)
RuntimeError: Not compiled with GPU support

```
</details>

---
I would appreciate any help on that,
Thanks!

**Comment by vedanuj** [comment]
Can you share the details of your environment? It seems the installation cannot find GPUs.

**Comment by guanyuhang8866** [comment]
> 您可以分享环境的详细信息吗？看来安装找不到GPU。



> Can you share the details of your environment? It seems the installation cannot find GPUs.

I had the same problem，and this is the information when i install  vqa-maskrcnn-benchmark:

running develop
running egg_info
writing maskrcnn_benchmark.egg-info/PKG-INFO
writing dependency_links to maskrcnn_benchmark.egg-info/dependency_links.txt
writing top-level names to maskrcnn_benchmark.egg-info/top_level.txt
reading manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
writing manifest file 'maskrcnn_benchmark.egg-info/SOURCES.txt'
running build_ext
building 'maskrcnn_benchmark._C' extension
Emitting ninja build file /disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /usr/local/miniconda3/envs/mmf/compiler_compat -L/usr/local/miniconda3/envs/mmf/lib -Wl,-rpath=/usr/local/miniconda3/envs/mmf/lib -Wl,--no-as-needed -Wl,--sysroot=/ /disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/build/temp.linux-x86_64-3.7/disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.o /disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/build/temp.linux-x86_64-3.7/disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.o /disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/build/temp.linux-x86_64-3.7/disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.o -L/usr/local/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so -> maskrcnn_benchmark
Creating /usr/local/miniconda3/envs/mmf/lib/python3.7/site-packages/maskrcnn-benchmark.egg-link (link to .)
Adding maskrcnn-benchmark 0.1 to easy-install.pth file

Installed /disk2/csworkspace/DRIVENDATA/vqa-maskrcnn-benchmark
Processing dependencies for maskrcnn-benchmark==0.1
Finished processing dependencies for maskrcnn-benchmark==0.1
