### ISSUE TITLE
Segmentation fault when running the tests right after the installation

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#639]
Hello,

I obtained a `Segmentation fault (core dumped)` error when running the tests right after the installation. Please see the details below. Thank you in advance for your help!

## Instructions To Reproduce the Issue:

1. Clone the repo
```
git clone https://github.com/facebookresearch/mmf.git
```
2. Install in editable mode (locally):
```
cd mmf
pip install --user --no-cache-dir -e .
```
3. Run the tests:
```
pytest ./tests/
```

4. Output:
```
======================================================== test session starts =========================================================
platform linux -- Python 3.7.5, pytest-5.3.5, py-1.8.0, pluggy-0.13.0
rootdir: /home/user/code/mmf
plugins: doctestplus-0.4.0, remotedata-0.3.2, arraydiff-0.3, openfiles-0.4.0
collecting ... Fatal Python error: Segmentation fault

Thread 0x00007ff2e5679b80 (most recent call first):
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/home/user/code/mmf/mmf/datasets/multi_dataset_loader.py", line 10 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/home/user/code/mmf/mmf/datasets/__init__.py", line 7 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 953 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 953 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/home/user/code/mmf/mmf/modules/metrics.py", line 51 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/home/user/code/mmf/mmf/modules/__init__.py", line 3 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen imporSegmentation fault (core dumped)

```

## Environment:

Provide your environment information using the following command:
```
python -m torch.utils.collect_env
```

Output:

```
Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
GCC version: (GCC) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] numpydoc==0.9.1
[pip] torch==1.6.0+cu101
[pip] torchsummary==1.5.1
[pip] torchtext==0.5.0
[pip] torchvision==0.7.0+cu101
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37h516909a_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] nomkl                     3.0                           0    https://repo.anaconda.com/pkgs/free
[conda] numpy                     1.18.1           py37h94c655d_0  
[conda] numpy-base                1.18.1           py37h2f8d375_1  
[conda] numpydoc                  0.9.1                      py_0  
[conda] pyinterp                  0.3.2           mkl_py37he448baa_102    conda-forge
```

**Comment by netw0rkf10w** [comment]
It seems that MMF requested all the resources on the machine where launched it, but the user only has access to some of them:

```
OpenBLAS blas_thread_init: pthread_create failed for thread 95 of 96: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4096 max
Traceback (most recent call last):
  File "/home/user/.local/bin/mmf_predict", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "/home/user/.local/bin/mmf_predict", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/gpfs7kro/gpfslocalsup/pub/anaconda-py3/2019.10/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 92, in load
    module = import_module(match.group('module'))
  File "/gpfslocalsup/pub/anaconda-py3/2019.10/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/code/mmf/mmf_cli/predict.py", line 6, in <module>
    from mmf_cli.run import run
  File "/home/user/code/mmf/mmf_cli/run.py", line 9, in <module>
    from mmf.common.registry import registry
  File "/home/user/code/mmf/mmf/__init__.py", line 5, in <module>
    from mmf import utils, common, modules, datasets, models
  File "/home/user/code/mmf/mmf/modules/__init__.py", line 3, in <module>
    import mmf.modules.metrics
  File "/home/user/code/mmf/mmf/modules/metrics.py", line 51, in <module>
    from mmf.datasets.processors.processors import EvalAIAnswerProcessor
  File "/home/user/code/mmf/mmf/datasets/__init__.py", line 7, in <module>
    from .multi_dataset_loader import MultiDatasetLoader
  File "/home/user/code/mmf/mmf/datasets/multi_dataset_loader.py", line 10, in <module>
Segmentation fault (core dumped)
```

**Comment by netw0rkf10w** [comment]
Apparently the issues lies in the restrictions of my account, as suggested in the above message.
