### ISSUE TITLE
BUTD prediction: omegaconf.errors.ConfigAttributeError: Key 'in_dim' in not in struct

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/mmf#646]
## Instructions To Reproduce the Issue:

After a fresh installation, I tried running the provided pretrained BUTD model, following the [documentation](https://mmf.sh/docs/projects/butd/):

```
mmf_predict config=projects/butd/configs/coco/beam_search.yaml \
    model=butd \
    dataset=coco \
    run_type=val \
    checkpoint.resume_zoo=butd
```

After having downloaded and extracted the data and the features, it produced an error:

```
2020-10-20T15:23:42 | torchtext.vocab: Loading vectors from /home/user/.cache/torch/mmf/glove.6B.300d.txt.pt
2020-10-20T15:23:43 | torchtext.vocab: Loading vectors from /home/user/.cache/torch/mmf/glove.6B.300d.txt.pt
2020-10-20T15:23:43 | torchtext.vocab: Loading vectors from /home/user/.cache/torch/mmf/glove.6B.300d.txt.pt
2020-10-20T15:23:47 | mmf.trainers.mmf_trainer: Loading model

Traceback (most recent call last):
  File "/home/user/.local/bin/mmf_predict", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "/home/user/code/mmf/mmf_cli/predict.py", line 15, in predict
    run(predict=True)
  File "/home/user/code/mmf/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/home/user/code/mmf/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/home/user/code/mmf/mmf/trainers/mmf_trainer.py", line 42, in load
    super().load()
  File "/home/user/code/mmf/mmf/trainers/base_trainer.py", line 30, in load
    self.load_model()
  File "/home/user/code/mmf/mmf/trainers/mmf_trainer.py", line 91, in load_model
    self.model = build_model(attributes)
  File "/home/user/code/mmf/mmf/utils/build.py", line 79, in build_model
    model.build()
  File "/home/user/code/mmf/mmf/models/butd.py", line 20, in build
    self._init_feature_encoders("image")
  File "/home/user/code/mmf/mmf/models/pythia.py", line 85, in _init_feature_encoders
    feat_encoder_config.params.in_dim = feature_dim
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 299, in __setattr__
    raise e
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 296, in __setattr__
    self.__set_impl(key, value)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 280, in __set_impl
    self._set_item_impl(key, value)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 340, in _set_item_impl
    self._validate_set(key, value)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 135, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 164, in _validate_set_merge_impl
    target = self._get_node(key)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 400, in _get_node
    self._validate_get(key)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 590, in format_and_raise
    raise_(ex, cause)
  File "/home/user/.local/lib/python3.7/site-packages/omegaconf/_utils.py", line 515, in raise_
    raise ex
omegaconf.errors.ConfigAttributeError: Key 'in_dim' in not in struct
	full_key: model_config.butd.image_feature_encodings[0].params.in_dim
	reference_type=Optional[Dict[Any, Any]]
	object_type=dict
```

Could you please help?

## Environment:

```
Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
GCC version: (GCC) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] numpydoc==0.9.1
[pip] torch==1.6.0+cu101
[pip] torchsummary==1.5.1
[pip] torchtext==0.5.0
[pip] torchvision==0.7.0+cu101
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37h516909a_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] nomkl                     3.0                           0    https://repo.anaconda.com/pkgs/free
[conda] numpy                     1.18.1           py37h94c655d_0  
[conda] numpy-base                1.18.1           py37h2f8d375_1  
[conda] numpydoc                  0.9.1                      py_0  
[conda] pyinterp                  0.3.2           mkl_py37he448baa_102    conda-forge
```

**Comment by apsdehal** [comment]
Hi, can you try patching #644 to see if it fixes your issue?

**Comment by netw0rkf10w** [comment]
@apsdehal Great. It's working now! Thank you!!
