### ISSUE TITLE
Problem when generating docker image

### ISSUE THREAD

**Issue by george-gca** [facebookresearch/mmf#669]
I've been trying to use mmf inside a docker image. Installed everything successfully, then when I try to run the first example from the documentation:
```python
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val
```
I get:
```
2020-10-31T02:43:35 | mmf.trainers.mmf_trainer: Loading datasets
2020-10-31T02:43:39 | transformers.tokenization_utils: loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/george.araujo/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
Traceback (most recent call last):
  File "/opt/conda/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/workspace/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/workspace/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/workspace/mmf/trainers/mmf_trainer.py", line 42, in load
    super().load()
  File "/workspace/mmf/trainers/base_trainer.py", line 29, in load
    self.load_datasets()
  File "/workspace/mmf/trainers/mmf_trainer.py", line 71, in load_datasets
    self.dataset_loader.load_datasets()
  File "/workspace/mmf/common/dataset_loader.py", line 17, in load_datasets
    self.train_dataset.load(self.config)
  File "/workspace/mmf/datasets/multi_dataset_loader.py", line 113, in load
    self.build_datasets(config)
  File "/workspace/mmf/datasets/multi_dataset_loader.py", line 128, in build_datasets
    dataset_instance = build_dataset(dataset, dataset_config, self.dataset_type)
  File "/workspace/mmf/utils/build.py", line 119, in build_dataset
    dataset = builder_instance.load_dataset(config, dataset_type)
  File "/workspace/mmf/datasets/base_dataset_builder.py", line 100, in load_dataset
    dataset.init_processors()
  File "/workspace/mmf/datasets/concat_dataset.py", line 35, in _call_all_datasets_func
    value = getattr(dataset, name)(*args, **kwargs)
  File "/workspace/mmf/datasets/base_dataset.py", line 59, in init_processors
    self.config.processors, reg_key, **extra_params
  File "/workspace/mmf/utils/build.py", line 352, in build_processors
    processor_instance = Processor(processor_params, *args, **kwargs)
  File "/workspace/mmf/datasets/processors/processors.py", line 157, in __init__
    self.processor = processor_class(params, *args, **kwargs)
  File "/workspace/mmf/datasets/processors/processors.py", line 1163, in __init__
    from mmf.utils.phoc import build_phoc
  File "/workspace/mmf/utils/phoc/__init__.py", line 3, in <module>
    from .build_phoc import build_phoc  # NoQA
  File "/workspace/mmf/utils/phoc/build_phoc.py", line 3, in <module>
    from .cphoc import build_phoc as _build_phoc_raw
ModuleNotFoundError: No module named 'mmf.utils.phoc.cphoc'
```

The dockerfile I am using, while giving the root folder of mmf as build context:
```docker
FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel

COPY . /workspace

# Environment variables
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    DPKG_INSTALL="dpkg -i" && \
    PIP_INSTALL="pip --no-cache-dir install --upgrade" && \
    DOWNLOAD_FILE="curl -LO" && \

# ==================================================================
# libraries via apt-get
# ------------------------------------------------------------------

    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \

    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        bc \
        build-essential \
        curl \
        git \
        libffi-dev \
        rsync \
        wget && \

# ==================================================================
# python libraries via pip
# ------------------------------------------------------------------

    $PIP_INSTALL \
        pip \
        wheel && \
    $PIP_INSTALL \
        comet-ml \
        cython \
        ipdb \
        ipython \
        kornia \
        matplotlib \
        opencv-python \
        pandas \
        prettytable \
        tensorboard \
        tqdm && \

# ==================================================================
# install mmf
# ------------------------------------------------------------------

    $PIP_INSTALL -e . && \

# ==================================================================
# config & cleanup
# ------------------------------------------------------------------

    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    /opt/conda/bin/conda clean -ya && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*

# TensorBoard ports
EXPOSE 6006 7000
```

**Comment by ytsheng** [comment]
Hi! Please try installing the latest mmf from source. For details: https://www.internalfb.com/intern/staticdocs/mmf/docs/getting_started/installation/

You might have installed the older version of mmf.

**Comment by george-gca** [comment]
But I am installing from source. If you look closely at my Dockerfile above you will see this part:
```dockerfile
# ==================================================================
# install mmf
# ------------------------------------------------------------------

    $PIP_INSTALL -e . && \

```
