### ISSUE TITLE
runtime error with Dataloader during m4c TextVQA inference

### ISSUE THREAD

**Issue by sweta125** [facebookresearch/mmf#674]
## ❓ Questions and Help

Hi, I am running the following command from the Quickstart page to use the pertained m4c model for TextVQA inference: 
mmf_predict config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=test \
    checkpoint.resume_zoo=m4c.textvqa.defaults

However, I keep running into the following error:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 29440) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/mmf_predict", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "/home/ubuntu/mmf/mmf_cli/predict.py", line 15, in predict
    run(predict=True)
  File "/home/ubuntu/mmf/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/home/ubuntu/mmf/mmf_cli/run.py", line 54, in main
    trainer.inference()
  File "/home/ubuntu/mmf/mmf/trainers/mmf_trainer.py", line 138, in inference
    self.prediction_loop(dataset)
  File "/home/ubuntu/mmf/mmf/trainers/core/evaluation_loop.py", line 62, in prediction_loop
    for batch in tqdm.tqdm(dataloader):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 29440) exited unexpectedly

**Comment by apsdehal** [comment]
Hi, this usually happens when you run out of memory. Can you post your system specs as mentioned in the bug template?

**Comment by sweta125** [comment]
Hi, I am using a g4dn.xlarge AWS EC2 Instance (Deep Learning AMI (Ubuntu 16.04)) with added EBS storage. 
(is there a link to the bug template?)

<img width="569" alt="Screen Shot 2020-11-02 at 3 44 29 PM" src="https://user-images.githubusercontent.com/34926001/97922599-5a89b580-1d22-11eb-8b06-b2bc862632b7.png">

**Comment by sweta125** [comment]
UPDATE: Resolved by setting training.num_workers = 1 (based on previous issues concerning memory)
