### ISSUE TITLE
Error in Training

### ISSUE THREAD

**Issue by nbhalla93** [facebookresearch/mmf#680]
## ❓ Questions and Help
Facing this issue while training the M4C Model
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val

![Screen Shot 2020-11-10 at 2 06 55 PM](https://user-images.githubusercontent.com/19534655/98719698-11f37d00-235e-11eb-8bcd-f13730534674.png)

**Comment by nbhalla93** [comment]
@apsdehal Can you please help me with this?

**Comment by apsdehal** [comment]
Hi, this is probably happening because you are running out of memory. FastText requires at least 8GB of memory to be loaded. Also, try setting `training.num_workers=0` to spawn less data workers.

**Comment by nbhalla93** [comment]
What is the right configuration of the system, to make this model work? I am getting this error too:
RuntimeError: CUDA out of memory. Tried to allocate 274.00 MiB (GPU 0; 11.17 GiB total capacity; 10.56 GiB already allocated; 85.44 MiB free; 10.73 GiB reserved in total by PyTorch)

**Comment by TownWilliam** [comment]
I also have the same problem during training the model. The method I solve it is that I reduce the `num_workers` , cut down  the `batch_size` from 128 to 64 or 32 etc. and increase the `max updates` from 24000 to 40000etc. (in order to keep the training quality). You could try to modify those three parameters in the configs of that model.

**Comment by apsdehal** [comment]
Thanks @TownWilliam for the suggestions. Those will definitely help. You can also try batch size of 16, which should be able to give reasonable results for M4C on TextVQA. On Quadro GP100, I can usually fit only a batch size of 64 which has 16GB GPU memory.

**Comment by soumyasj** [comment]
@TownWilliam even after following all the steps, I am still facing this error. I run the following command:

mmf_run dataset=textvqa   model=m4c   config=projects/m4c/configs/textvqa/defaults.yaml   env.save_dir=./save/m4c training.num_workers=0 training.batch_size=1

Traceback (most recent call last):                                                                                                                    
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data                        
    data = self._data_queue.get(timeout=timeout)                                                                                                      
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/lib/python3.7/multiprocessing/queues.py", line 104, in get                                        
    if not self._poll(timeout):                                                                                                                       
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/lib/python3.7/multiprocessing/connection.py", line 257, in poll                                   
    return self._poll(timeout)                                                                                                                        
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 14469) is killed by signal: Killed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home2/soumyajahagirdar/miniconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home2/soumyajahagirdar/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/home2/soumyajahagirdar/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home2/soumyajahagirdar/mmf/mmf/trainers/mmf_trainer.py", line 145, in train
    self.training_loop()
  File "/home2/soumyajahagirdar/mmf/mmf/trainers/core/training_loop.py", line 33, in training_loop
    self.run_training_epoch()
  File "/home2/soumyajahagirdar/mmf/mmf/trainers/core/training_loop.py", line 77, in run_training_epoch
    for idx, batch in enumerate(self.train_loader):
  File "/home2/soumyajahagirdar/mmf/mmf/datasets/multi_dataset_loader.py", line 198, in __next__
    next_batch = next(self.current_iterator)
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home2/soumyajahagirdar/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 14469) exited unexpectedly

I also tried with training.num_workers=1 but it is till throwing the same error.

Any help would be much appreciated.

**Comment by TownWilliam** [comment]
Sorry @soumyasj , I have no idea for this condition because you did reduced the number of `batch size` and `num_workers`. Maybe the device is too old for deep learning or has not enough memory(Actually I guess it would be not.... )

In conclusion, I do not know the details of the model well.  All I could conclude are the following rough guess:

1)Pherhaps there are some neglected parameters, such as the parameters in the `config/defualt.yaml`  were modified in the previous.  
2)How many devices such as GPU or CPU are used to train the M4C model? If you use more than one devices for training, the program in the `mmf/mmf_cli/run.py` would tends to train the model  with distributed style. This may make some unexpected condition during training.
3) Does this error always appears no matter which `model` or `dataset` used in command lines? I could not know if it is caused by the config file of M4C, or it is caused by the device itself...
