### ISSUE TITLE
mmf_convert_hm gives FileNotFoundError

### ISSUE THREAD

**Issue by JoshuaPlacidi** [facebookresearch/mmf#683]
## ❓ Questions and Help
Hi, I am trying to learn mmf and am following this [tutorial](https://medium.com/pytorch/bootstrapping-a-multimodal-project-using-mmf-a-pytorch-powered-multimodal-framework-464f75164af7).

I have installed mmf (on windows) and downloaded the hateful memes dataset. I am trying to run the tutorial in a Jupyter notebook. I have the following code:

`from mmf.utils.env import setup_imports`
`setup_imports()`
`from mmf.utils.build import build_dataset`

`!mmf_convert_hm --zip_file=F:/hm.zip --password=[password]`

mmf_convert_hm takes some time to run (~5 mins) then errors with the following:

```
Data folder is C:\Users\Josh/.cache\torch\mmf\data
Zip path is F:/hm.zip
Starting checksum for hm.zip
Checksum successful
Copying F:/hm.zip
Unzipping F:/hm.zip
Extracting the zip can take time. Sit back and relax.

Traceback (most recent call last):
  File "f:\mmf\mmf_cli\hm_convert.py", line 195, in decompress_zip
    subprocess.run(command, check=True)
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Josh\anaconda3\Scripts\mmf_convert_hm-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_convert_hm')())
  File "f:\mmf\mmf_cli\hm_convert.py", line 206, in main
    converter.convert()
  File "f:\mmf\mmf_cli\hm_convert.py", line 135, in convert
    self.decompress_zip(
  File "f:\mmf\mmf_cli\hm_convert.py", line 200, in decompress_zip
    obj.extractall(path=dest)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1646, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1701, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Users\Josh\anaconda3\lib\shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 939, in read
    data = self._read1(n)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1007, in _read1
    data += self._read2(n - len(data))
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1042, in _read2
    raise EOFError
EOFError

Data folder is C:\Users\Josh/.cache\torch\mmf\data
Zip path is F:\hm.zip
Starting checksum for hm.zip
Checksum successful
Copying F:\hm.zip
Unzipping F:\hm.zip
Extracting the zip can take time. Sit back and relax.

Traceback (most recent call last):
  File "f:\mmf\mmf_cli\hm_convert.py", line 195, in decompress_zip
    subprocess.run(command, check=True)
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Josh\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Josh\anaconda3\Scripts\mmf_convert_hm-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_convert_hm')())
  File "f:\mmf\mmf_cli\hm_convert.py", line 206, in main
    converter.convert()
  File "f:\mmf\mmf_cli\hm_convert.py", line 135, in convert
    self.decompress_zip(
  File "f:\mmf\mmf_cli\hm_convert.py", line 200, in decompress_zip
    obj.extractall(path=dest)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1646, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1701, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Users\Josh\anaconda3\lib\shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 939, in read
    data = self._read1(n)
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1007, in _read1
    data += self._read2(n - len(data))
  File "C:\Users\Josh\anaconda3\lib\zipfile.py", line 1042, in _read2
    raise EOFError
EOFError
```

Any help is much appreciated.

**Comment by vedanuj** [comment]
Are you able to extract the zip file manually with the password?

**Comment by JoshuaPlacidi** [comment]
Hi, yes I can extract it manually. I have also tried to run the mmf_convert_hm via cli and it just runs forever with "Extracting the zip can take time. Sit back and relax." and never completes.

**Comment by JoshuaPlacidi** [comment]
> Are you able to extract the zip file manually with the password?

Hi, yes I can extract it manually. I have also tried to run the mmf_convert_hm via cli and it just runs forever with "Extracting the zip can take time. Sit back and relax." and never completes.

**Comment by apsdehal** [comment]
Yes, this is expected on Windows given that windows doesn't have unzip command. Normal python zipfile module is very slow. You can try running in ubuntu terminal for windows to see if it helps. Alternatively, you can manually extract the files and place it in a way how the repo expects.

**Comment by JoshuaPlacidi** [comment]
@apsdehal Thanks for the help. Ill try a manual extraction first. Do you know where I can find out how the repo is expecting the data?

**Comment by JoshuaPlacidi** [comment]
Command does eventually successfully complete on windows just takes a while to run.
