### ISSUE TITLE
Error in code running，looking forward to your answer.

### ISSUE THREAD

**Issue by JerphyZ** [facebookresearch/mmf#692]
## ❓ Questions and Help
(mmf) J:\mmf>mmf_run config=projects/lorra/configs/vqa2/defaults.yaml run_type=train_val dataset=vqa2 model=lorra
2020-11-19T12:15:20 | mmf.utils.configuration: Overriding option config to projects/lorra/configs/vqa2/defaults.yaml
2020-11-19T12:15:20 | mmf.utils.configuration: Overriding option run_type to train_val
2020-11-19T12:15:20 | mmf.utils.configuration: Overriding option datasets to vqa2
2020-11-19T12:15:20 | mmf.utils.configuration: Overriding option model to lorra
2020-11-19T12:15:20 | mmf: Logging to: ./save\train.log
2020-11-19T12:15:20 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=projects/lorra/configs/vqa2/defaults.yaml', 'run_type=train_val', 'dataset=vqa2', 'model=lorra'])
2020-11-19T12:15:20 | mmf_cli.run: Torch version: 1.6.0
2020-11-19T12:15:20 | mmf.utils.general: CUDA Device 0 is: Quadro P6000
2020-11-19T12:15:20 | mmf_cli.run: Using seed 20473719
2020-11-19T12:15:20 | mmf.trainers.mmf_trainer: Loading datasets
2020-11-19T12:15:40 | torchtext.vocab: Loading vectors from C:\Users\Administrator/.cache\torch\mmf\glove.6B.300d.txt.pt
2020-11-19T12:15:42 | torchtext.vocab: Loading vectors from C:\Users\Administrator/.cache\torch\mmf\glove.6B.300d.txt.pt
2020-11-19T12:16:12 | mmf.trainers.mmf_trainer: Loading model
2020-11-19T12:16:23 | mmf.trainers.mmf_trainer: Loading optimizer
2020-11-19T12:16:23 | mmf.trainers.mmf_trainer: Loading metrics
WARNING 2020-11-19T12:16:24 | py.warnings: j:\mmf\mmf\utils\build.py:255: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

WARNING 2020-11-19T12:16:24 | py.warnings: j:\mmf\mmf\utils\build.py:255: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

WARNING 2020-11-19T12:16:24 | py.warnings: j:\mmf\mmf\utils\build.py:261: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

WARNING 2020-11-19T12:16:24 | py.warnings: j:\mmf\mmf\utils\build.py:261: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

2020-11-19T12:16:24 | mmf.trainers.mmf_trainer: ===== Model =====
2020-11-19T12:16:24 | mmf.trainers.mmf_trainer: LoRRA(
  (text_embeddings): ModuleList(
    (0): TextEmbedding(
      (module): AttentionTextEmbedding(
        (recurrent_unit): LSTM(300, 1024, batch_first=True)
        (dropout): Dropout(p=0, inplace=False)
        (conv1): Conv1d(1024, 512, kernel_size=(1,), stride=(1,))
        (conv2): Conv1d(512, 2, kernel_size=(1,), stride=(1,))
        (relu): ReLU()
      )
    )
  )
  (context_embeddings): ModuleList(
    (0): TextEmbedding(
      (module): Identity()
    )
  )
  (context_feature_encoders): ModuleList(
    (0): Identity()
  )
  (context_feature_embeddings_list): ModuleList(
    (0): ModuleList(
      (0): ImageFeatureEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=300, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0, inplace=False)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
  )
  (word_embedding): Embedding(75505, 300)
  (image_feature_encoders): ModuleList(
    (0): FinetuneFasterRcnnFpnFc7(
      (lc): Linear(in_features=2048, out_features=2048, bias=True)
    )
    (1): Identity()
  )
  (image_feature_embeddings_list): ModuleList(
    (0): ModuleList(
      (0): ImageFeatureEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0, inplace=False)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
    (1): ModuleList(
      (0): ImageFeatureEmbedding(
        (image_attention_model): AttentionLayer(
          (module): TopDownAttention(
            (combination_layer): ModalCombineLayer(
              (module): NonLinearElementMultiply(
                (fa_image): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (fa_txt): ReLUWithWeightNormFC(
                  (layers): Sequential(
                    (0): Linear(in_features=2048, out_features=5000, bias=True)
                    (1): ReLU()
                  )
                )
                (dropout): Dropout(p=0, inplace=False)
              )
            )
            (transform): TransformLayer(
              (module): LinearTransform(
                (lc): Linear(in_features=5000, out_features=1, bias=True)
              )
            )
          )
        )
      )
    )
  )
  (image_text_multi_modal_combine_layer): ModalCombineLayer(
    (module): NonLinearElementMultiply(
      (fa_image): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=4096, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (fa_txt): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=2048, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (fa_context): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=350, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (dropout): Dropout(p=0, inplace=False)
    )
  )
  (classifier): ClassifierLayer(
    (module): LogitClassifier(
      (f_o_text): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=10000, out_features=300, bias=True)
          (1): ReLU()
        )
      )
      (f_o_image): ReLUWithWeightNormFC(
        (layers): Sequential(
          (0): Linear(in_features=10000, out_features=5000, bias=True)
          (1): ReLU()
        )
      )
      (linear_text): Linear(in_features=300, out_features=3179, bias=True)
      (linear_image): Linear(in_features=5000, out_features=3179, bias=True)
    )
  )
  (losses): Losses(
    (losses): ModuleList(
      (0): MMFLoss(
        (loss_criterion): LogitBinaryCrossEntropy()
      )
    )
  )
)
2020-11-19T12:16:24 | mmf.utils.general: Total Parameters: 187895349. Trained Parameters: 187895349
2020-11-19T12:16:24 | mmf.trainers.core.training_loop: Starting training...
Traceback (most recent call last):
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "j:\mmf\mmf_cli\run.py", line 122, in run
    main(configuration, predict=predict)
  File "j:\mmf\mmf_cli\run.py", line 56, in main
    trainer.train()
  File "j:\mmf\mmf\trainers\mmf_trainer.py", line 123, in train
    self.training_loop()
  File "j:\mmf\mmf\trainers\core\training_loop.py", line 31, in training_loop
    self.run_training_epoch()
  File "j:\mmf\mmf\trainers\core\training_loop.py", line 75, in run_training_epoch
    for idx, batch in enumerate(self.train_loader):
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "j:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 233, in _load
    img_id_idx = self.image_id_indices[str(image_id).encode()]
KeyError: b'train2014\\372460.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\Anaconda3-2019.03-Windows-x86_64\envs\mmf\lib\site-packages\torch\utils\data\dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "j:\mmf\mmf\datasets\builders\vqa2\dataset.py", line 53, in __getitem__
    return self.load_item(idx)
  File "j:\mmf\mmf\datasets\builders\vqa2\dataset.py", line 90, in load_item
    features = self.features_db[idx]
  File "j:\mmf\mmf\datasets\databases\features_database.py", line 91, in __getitem__
    return self.get(image_info)
  File "j:\mmf\mmf\datasets\databases\features_database.py", line 99, in get
    return self.from_path(feature_path)
  File "j:\mmf\mmf\datasets\databases\features_database.py", line 107, in from_path
    features, infos = self._get_image_features_and_info(path)
  File "j:\mmf\mmf\datasets\databases\features_database.py", line 80, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "j:\mmf\mmf\datasets\databases\features_database.py", line 65, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "j:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 95, in read
    return self.feat_reader.read(image_feat_path)
  File "j:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 157, in read
    image_info = self._load(image_feat_path)
  File "j:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 237, in _load
    img_id_idx = self.image_id_indices[image_id]
KeyError: b'train2014\\372460.pth'

What is the reason for this error? Do I need to download the image dataset from this command line? But in vqa2/defaults.yaml use_images is false. Or there is something wrong with my datasets structure? My datasets structure: 
data_dir: J:/.cache/torch/mmf/data/datasets/
- coco
     - features:
        - coco/defaults/features/trainval2014.lmdb
        - coco/defaults/features/test2015.lmdb
     - annotations:
        - coco/defaults/annotations/imdb_karpathy_train.npy
        - coco/defaults/annotations/imdb_karpathy_val.npy
        - coco/defaults/annotations/imdb_karpathy_test.npy
     - extras
        - vocabs
             - vocabulary_100k.txt
             - vocabulary_captioning_thresh5.txt
- vqa2
     - annotations
        - vqa2/defaults/annotations/imdb_train2014.npy
        - vqa2/defaults/annotations/imdb_val2014.npy
        - vqa2/defaults/annotations/imdb_test2015.npy
     - extras
        - vocabs
             - answer_vqa.txt
             - vocabulary_100k.txt
             - vocabulary_vqa.txt
     - features
Looking forward to your answer！Thanks！

**Comment by ytsheng** [comment]
It looks like your dataset structure is different from mine, mmf should have automatically downloaded the datasets if it cannot find the dataset. Here is my dataset structure for example, under: ```~/.cache/torch/mmf/data/datasets/coco```, I have:
```
- defaults
  - annotations
    - imdb_karpathy_train.npy
    - imdb_karpathy_test.npy
    - imdb_karpathy_val.npy
  - extras
    - vocab
      - vocabulary_100k.txt
      - vocabulary_captioning_thresh5.txt
  - features
    - trainval2014.lmdb
    - test2015.lmdb
```
