### ISSUE TITLE
Error when train pythia in vizwiz dataset(AssertionError: Number of feature encoders, 2 are not equal to number of features, 1.)

### ISSUE THREAD

**Issue by vincent1rookie** [facebookresearch/mmf#697]
I tried to run 
```
mmf_run config=projects/pythia/configs/vizwiz/defaults.yaml model=pythia dataset=vizwiz run_type=train_val
```
But I got:

```
2020-11-25T17:07:05 | mmf.utils.configuration: Overriding option config to /home/vincentzyxu/mmf/mmf/projects/pythia/configs/vizwiz/defaults.yaml
2020-11-25T17:07:05 | mmf.utils.configuration: Overriding option model to pythia
2020-11-25T17:07:05 | mmf.utils.configuration: Overriding option datasets to vizwiz
2020-11-25T17:07:05 | mmf.utils.configuration: Overriding option run_type to train_val
2020-11-25T17:07:06 | mmf.utils.distributed: Distributed Init (Rank 3): tcp://localhost:11886
2020-11-25T17:07:06 | mmf.utils.distributed: Distributed Init (Rank 0): tcp://localhost:11886
2020-11-25T17:07:06 | mmf.utils.distributed: Distributed Init (Rank 2): tcp://localhost:11886
2020-11-25T17:07:06 | mmf.utils.distributed: Initialized Host x-server1 as Rank 2
2020-11-25T17:07:06 | mmf.utils.distributed: Distributed Init (Rank 1): tcp://localhost:11886
2020-11-25T17:07:06 | mmf.utils.distributed: Initialized Host x-server1 as Rank 1
2020-11-25T17:07:07 | mmf.utils.distributed: Initialized Host x-server1 as Rank 3
2020-11-25T17:07:07 | mmf.utils.distributed: Initialized Host x-server1 as Rank 0
2020-11-25T17:07:09 | mmf: Logging to: ./save/train.log
2020-11-25T17:07:09 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=/home/vincentzyxu/mmf/mmf/projects/pythia/configs/vizwiz/defaults.yaml', 'model=pythia', 'dataset=vizwiz', 'run_type=train_val'])
2020-11-25T17:07:09 | mmf_cli.run: Torch version: 1.6.0
2020-11-25T17:07:09 | mmf.utils.general: CUDA Device 0 is: TITAN Xp
2020-11-25T17:07:09 | mmf_cli.run: Using seed 9509087
2020-11-25T17:07:09 | mmf.trainers.mmf_trainer: Loading datasets
2020-11-25T17:07:10 | torchtext.vocab: Loading vectors from /home/vincentzyxu/.cache/torch/mmf/glove.6B.300d.txt.pt
2020-11-25T17:07:13 | torchtext.vocab: Loading vectors from /home/vincentzyxu/.cache/torch/mmf/glove.6B.300d.txt.pt
2020-11-25T17:07:17 | mmf.trainers.mmf_trainer: Loading model
2020-11-25T17:07:19 | mmf.trainers.mmf_trainer: Loading optimizer
2020-11-25T17:07:19 | mmf.trainers.mmf_trainer: Loading metrics
WARNING 2020-11-25T17:07:19 | py.warnings: /home/vincentzyxu/mmf/mmf/utils/distributed.py:272: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  builtin_warn(*args, **kwargs)

WARNING 2020-11-25T17:07:19 | py.warnings: /home/vincentzyxu/mmf/mmf/utils/distributed.py:272: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  builtin_warn(*args, **kwargs)

WARNING 2020-11-25T17:07:19 | py.warnings: /home/vincentzyxu/mmf/mmf/utils/distributed.py:272: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  builtin_warn(*args, **kwargs)

WARNING 2020-11-25T17:07:19 | py.warnings: /home/vincentzyxu/mmf/mmf/utils/distributed.py:272: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  builtin_warn(*args, **kwargs)

2020-11-25T17:07:19 | mmf.trainers.mmf_trainer: ===== Model =====
2020-11-25T17:07:19 | mmf.trainers.mmf_trainer: DistributedDataParallel(
  (module): Pythia(
    (word_embedding): Embedding(75505, 300)
    (text_embeddings): ModuleList(
      (0): TextEmbedding(
        (module): AttentionTextEmbedding(
          (recurrent_unit): LSTM(300, 1024, batch_first=True)
          (dropout): Dropout(p=0, inplace=False)
          (conv1): Conv1d(1024, 512, kernel_size=(1,), stride=(1,))
          (conv2): Conv1d(512, 2, kernel_size=(1,), stride=(1,))
          (relu): ReLU()
        )
      )
    )
    (image_feature_encoders): ModuleList(
      (0): FinetuneFasterRcnnFpnFc7(
        (lc): Linear(in_features=2048, out_features=2048, bias=True)
      )
      (1): Identity()
    )
    (image_feature_embeddings_list): ModuleList(
      (0): ModuleList(
        (0): ImageFeatureEmbedding(
          (image_attention_model): AttentionLayer(
            (module): TopDownAttention(
              (combination_layer): ModalCombineLayer(
                (module): NonLinearElementMultiply(
                  (fa_image): ReLUWithWeightNormFC(
                    (layers): Sequential(
                      (0): Linear(in_features=2048, out_features=5000, bias=True)
                      (1): ReLU()
                    )
                  )
                  (fa_txt): ReLUWithWeightNormFC(
                    (layers): Sequential(
                      (0): Linear(in_features=2048, out_features=5000, bias=True)
                      (1): ReLU()
                    )
                  )
                  (dropout): Dropout(p=0, inplace=False)
                )
              )
              (transform): TransformLayer(
                (module): LinearTransform(
                  (lc): Linear(in_features=5000, out_features=1, bias=True)
                )
              )
            )
          )
        )
      )
      (1): ModuleList(
        (0): ImageFeatureEmbedding(
          (image_attention_model): AttentionLayer(
            (module): TopDownAttention(
              (combination_layer): ModalCombineLayer(
                (module): NonLinearElementMultiply(
                  (fa_image): ReLUWithWeightNormFC(
                    (layers): Sequential(
                      (0): Linear(in_features=2048, out_features=5000, bias=True)
                      (1): ReLU()
                    )
                  )
                  (fa_txt): ReLUWithWeightNormFC(
                    (layers): Sequential(
                      (0): Linear(in_features=2048, out_features=5000, bias=True)
                      (1): ReLU()
                    )
                  )
                  (dropout): Dropout(p=0, inplace=False)
                )
              )
              (transform): TransformLayer(
                (module): LinearTransform(
                  (lc): Linear(in_features=5000, out_features=1, bias=True)
                )
              )
            )
          )
        )
      )
    )
    (image_text_multi_modal_combine_layer): ModalCombineLayer(
      (module): NonLinearElementMultiply(
        (fa_image): ReLUWithWeightNormFC(
          (layers): Sequential(
            (0): Linear(in_features=4096, out_features=5000, bias=True)
            (1): ReLU()
          )
        )
        (fa_txt): ReLUWithWeightNormFC(
          (layers): Sequential(
            (0): Linear(in_features=2048, out_features=5000, bias=True)
            (1): ReLU()
          )
        )
        (dropout): Dropout(p=0, inplace=False)
      )
    )
    (classifier): ClassifierLayer(
      (module): LogitClassifier(
        (f_o_text): ReLUWithWeightNormFC(
          (layers): Sequential(
            (0): Linear(in_features=5000, out_features=300, bias=True)
            (1): ReLU()
          )
        )
        (f_o_image): ReLUWithWeightNormFC(
          (layers): Sequential(
            (0): Linear(in_features=5000, out_features=5000, bias=True)
            (1): ReLU()
          )
        )
        (linear_text): Linear(in_features=300, out_features=7371, bias=True)
        (linear_image): Linear(in_features=5000, out_features=7371, bias=True)
      )
    )
    (losses): Losses(
      (losses): ModuleList(
        (0): MMFLoss(
          (loss_criterion): LogitBinaryCrossEntropy()
        )
      )
    )
  )
)
2020-11-25T17:07:19 | mmf.utils.general: Total Parameters: 170111328. Trained Parameters: 170111328
2020-11-25T17:07:19 | mmf.trainers.core.training_loop: Starting training...
Traceback (most recent call last):
  File "/home/vincentzyxu/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/vincentzyxu/mmf/mmf_cli/run.py", line 118, in run
    nprocs=config.distributed.world_size,
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/vincentzyxu/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/vincentzyxu/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/vincentzyxu/mmf/mmf/trainers/mmf_trainer.py", line 123, in train
    self.training_loop()
  File "/home/vincentzyxu/mmf/mmf/trainers/core/training_loop.py", line 31, in training_loop
    self.run_training_epoch()
  File "/home/vincentzyxu/mmf/mmf/trainers/core/training_loop.py", line 89, in run_training_epoch
    report = self.run_training_batch(batch, num_batches_for_this_update)
  File "/home/vincentzyxu/mmf/mmf/trainers/core/training_loop.py", line 159, in run_training_batch
    report = self._forward(batch)
  File "/home/vincentzyxu/mmf/mmf/trainers/core/training_loop.py", line 176, in _forward
    model_output = self.model(prepared_batch)
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/vincentzyxu/mmf/mmf/models/base_model.py", line 170, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/vincentzyxu/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vincentzyxu/mmf/mmf/models/pythia.py", line 299, in forward
    "image", sample_list, text_embedding_total
  File "/home/vincentzyxu/mmf/mmf/models/pythia.py", line 246, in process_feature_embedding
    "to number of features, {}.".format(len(feature_encoders), len(features))
AssertionError: Number of feature encoders, 2 are not equal to number of features, 1.

```

**Comment by ytsheng** [comment]
Hi @vincent1rookie, thanks for using mmf!

Our pythia implementation uses both the grid features together with the bottom-up features as indicated in section 2.5 of the Pythia [paper](https://arxiv.org/abs/1807.09956). So, we are expecting 2 image feature vectors are provided for this model. If you only wish to provide 1 image feature, you can remove 1 image_feature_encoder in the config so that the number of image features and image_feature_encoders match.

May I ask what is your specific use case? [Here](https://dl.fbaipublicfiles.com/pythia/pretrained_models/vizwiz/pythia_pretrained_vqa2.pth) is a vqa2 pretrained vizwiz model using pythia, just in case it is helpful to you.

**Comment by vincent1rookie** [comment]
> Hi @vincent1rookie, thanks for using mmf!
> 
> Our pythia implementation uses both the grid features together with the bottom-up features as indicated in section 2.5 of the Pythia [paper](https://arxiv.org/abs/1807.09956). So, we are expecting 2 image feature vectors should be provided for this model. If you only wish to provide 1 image feature, you can remove 1 image_feature_encoder in the config so that the number of image features and image_feature_encoders match.
> 
> May I ask what is your specific use case? [Here](https://dl.fbaipublicfiles.com/pythia/pretrained_models/vizwiz/pythia_pretrained_vqa2.pth) is a vqa2 pretrained vizwiz model using pythia, just in case it is helpful to you.

Thank you for your reply. I was using exactly the vqa2 pretrained vizwiz model you mentioned, and was using the default config in project/pythia/vizwiz. Does it mean the pretrained model is not consistent with the vizwiz dataset or or I just change the config somewhere?

**Comment by KevinQian97** [comment]
Hi, I am encountered with this problem too. Would you mind giving an explicit modification steps?

**Comment by CCYChongyanChen** [comment]
I have encountered this problem too.  Any further help is appreciated. Thanks!
