### ISSUE TITLE
mmf_run showing problem while training

### ISSUE THREAD

**Issue by naveenchoudhary839** [facebookresearch/mmf#790]
## ❓ Questions and Help
**When i am running the following command,**
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val

**It is showing the error as,**
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option config to projects/m4c/configs/textvqa/defaults.yaml
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option datasets to textvqa
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option model to m4c
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option run_type to train_val
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option training.batch_size to 32
2021-02-27T13:58:58 | mmf.utils.configuration: Overriding option training.max_updates to 44000
/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/cuda/__init__.py:125: UserWarning: 
Tesla K20c with CUDA capability sm_35 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the Tesla K20c GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2021-02-27T13:59:02 | mmf.utils.distributed: XLA Mode:None
2021-02-27T13:59:02 | mmf.utils.distributed: Distributed Init (Rank 0): tcp://localhost:17103
/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/cuda/__init__.py:125: UserWarning: 
Tesla K20c with CUDA capability sm_35 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the Tesla K20c GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2021-02-27T13:59:03 | mmf.utils.distributed: XLA Mode:None
2021-02-27T13:59:03 | mmf.utils.distributed: Distributed Init (Rank 1): tcp://localhost:17103
2021-02-27T13:59:03 | mmf.utils.distributed: Initialized Host nsl-30 as Rank 1
2021-02-27T13:59:03 | mmf.utils.distributed: Initialized Host nsl-30 as Rank 0
Traceback (most recent call last):
  File "/home/naveen/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/naveen/mmf/mmf_cli/run.py", line 129, in run
    nprocs=config.distributed.world_size,
  File "/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/naveen/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/naveen/mmf/mmf_cli/run.py", line 33, in main
    distributed_init(config)
  File "/home/naveen/mmf/mmf/utils/distributed.py", line 283, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/home/naveen/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 936, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8

**I am running the code on a remote gpu.
Can You please help in resolving the issue**

**Comment by vedanuj** [comment]
This seems to be an NCCL and pytorch version related issue. Please raise the issue in pytorch repo or ask in the forums.

**Comment by apsdehal** [comment]
Also, in the logs it has a warning which is showing that the exact problem:

> UserWarning: Tesla K20c with CUDA capability sm_35 is not compatible with the current PyTorch installation.
> The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
> If you want to use the Tesla K20c GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
