### ISSUE TITLE
Error while Training - Textvqa

### ISSUE THREAD

**Issue by Mano2610** [facebookresearch/mmf#792]
Hi,
I am getting the below error when I tried to run the mmf-facebook.
I just downloaded the github and ran the commands , getting the below error.
(mmf) D:\PROJECT\New folder\mmf>mmf_run config=projects/lorra/configs/textvqa/defaults.yaml \    datasets=textvqa \    model=lorra \    run_type=train_val
2021-03-02T15:14:39 | mmf.utils.configuration: Overriding option config to projects/lorra/configs/textvqa/defaults.yaml
Traceback (most recent call last):
  File "C:\Users\kvman\anaconda3\envs\mmf\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "d:\project\new folder\mmf\mmf_cli\run.py", line 91, in run
    configuration = Configuration(args)
  File "d:\project\new folder\mmf\mmf\utils\configuration.py", line 224, in __init__
    self.config = self._merge_with_dotlist(self.config, args.opts)
  File "d:\project\new folder\mmf\mmf\utils\configuration.py", line 392, in _merge_with_dotlist
    for opt, value in opt_values:
ValueError: not enough values to unpack (expected 2, got 1)

Before running the above commands, do I need to download the features. If so, where to download it?

_Originally posted by @Mano2610 in https://github.com/facebookresearch/mmf/issues/375#issuecomment-788993971_

**Comment by apsdehal** [comment]
Hi,

Can you run this: `mmf_run config=projects/lorra/configs/textvqa/defaults.yaml datasets=textvqa model=lorra  run_type=train_val` (without the \)?

**Comment by Mano2610** [comment]
Yes, now the datasets are downloading...
But this is Lorra model, Can we try using m4c instead of lorra

**Comment by apsdehal** [comment]
Sure, please follow M4C project's instructions: https://mmf.sh/docs/projects/m4c

**Comment by Mano2610** [comment]
While Training the model, I am getting the following error,

2021-03-09T19:52:05 | mmf.utils.general: Total Parameters: 90850184. Trained Parameters: 90850184
2021-03-09T19:52:05 | mmf.trainers.core.training_loop: Starting training...
Traceback (most recent call last):
  File "C:\Users\kvman\anaconda3\envs\mmf\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "d:\project\new folder\mmf\mmf_cli\run.py", line 133, in run
    main(configuration, predict=predict)
  File "d:\project\new folder\mmf\mmf_cli\run.py", line 56, in main
    trainer.train()
  File "d:\project\new folder\mmf\mmf\trainers\mmf_trainer.py", line 132, in train
    self.training_loop()
  File "d:\project\new folder\mmf\mmf\trainers\core\training_loop.py", line 31, in training_loop
    self.run_training_epoch()
  File "d:\project\new folder\mmf\mmf\trainers\core\training_loop.py", line 74, in run_training_epoch
    for idx, batch in enumerate(self.train_loader):
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data    data.reraise()
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "d:\project\new folder\mmf\mmf\datasets\databases\readers\feature_readers.py", line 231, in _load
    image_id = int(split.split("_")[-1])
ValueError: invalid literal for int() with base 10: 'train\\277c9771210899ac'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kvman\anaconda3\envs\mmf\lib\site-packages\torch\utils\data\dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "d:\project\new folder\mmf\mmf\datasets\builders\textvqa\dataset.py", line 100, in __getitem__
    features = self.features_db[idx]
  File "d:\project\new folder\mmf\mmf\datasets\databases\features_database.py", line 91, in __getitem__
    return self.get(image_info)
  File "d:\project\new folder\mmf\mmf\datasets\databases\features_database.py", line 99, in get
    return self.from_path(feature_path)
  File "d:\project\new folder\mmf\mmf\datasets\databases\features_database.py", line 107, in from_path
    features, infos = self._get_image_features_and_info(path)
  File "d:\project\new folder\mmf\mmf\datasets\databases\features_database.py", line 80, in _get_image_features_and_info    image_feats, infos = self._read_features_and_info(feat_file)
  File "d:\project\new folder\mmf\mmf\datasets\databases\features_database.py", line 65, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "d:\project\new folder\mmf\mmf\datasets\databases\readers\feature_readers.py", line 95, in read
    return self.feat_reader.read(image_feat_path)
  File "d:\project\new folder\mmf\mmf\datasets\databases\readers\feature_readers.py", line 158, in read
    image_info = self._load(image_feat_path)
  File "d:\project\new folder\mmf\mmf\datasets\databases\readers\feature_readers.py", line 238, in _load
    img_id_idx = self.image_id_indices[image_id]
KeyError: b'train\\277c9771210899ac'

Is this error is due to any pc config?
What should I do to resolve it?
