### ISSUE TITLE
While training Movie_mcan, model seems to be stuck at "Evaluation time. Running on full validation set..."

### ISSUE THREAD

**Issue by ifmaq1** [facebookresearch/mmf#812]
I am training Movie_mcan model on 2 GPUS 

**I changed the backend from NCCL to gloo** because my training was getting stuck with NCCL. Also, I am using **8 batch size** due to 16GB RAM and 2 Tesla K-80 GPUS(each with 11 GB memory) and num_worker=2 is working for me.

When I run a command

**CUDA_VISIBLE_DEVICES=0,1 mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml \model=movie_mcan \dataset=vqa2 \run_type=train \checkpoint.resume=True \training.num_workers=2**

The training details are as follows:

2021-03-12T15:46:12 | mmf.utils.general: Total Parameters: 254918110. Trained Parameters: 254918110
2021-03-12T15:46:12 | mmf.trainers.core.training_loop: Starting training...
2021-03-12T15:52:30 | mmf.trainers.callbacks.logistics: progress: 5100/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 20.1549, train/total_loss: 20.1549, train/total_loss/avg: 20.1549, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5100, iterations: 5100, max_updates: 236000, lr: 0.00002, ups: 0.27, **time: 06m 17s 344ms**, time_since_start: 06m 51s 100ms, eta: 1863h 06m 21s 108ms
2021-03-12T15:57:56 | mmf.trainers.callbacks.logistics: progress: 5200/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 21.8194, train/total_loss: 20.1549, train/total_loss/avg: 21.8194, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5200, iterations: 5200, max_updates: 236000, lr: 0.00002, ups: 0.31, **time: 05m 26s 277ms**, time_since_start: 12m 17s 392ms, eta: 1610h 16m 12s 756ms
2021-03-12T16:03:27 | mmf.trainers.callbacks.logistics: progress: 5300/236000, train/vqa2/triple_logit_bce: 20.7160, train/vqa2/triple_logit_bce/avg: 21.4516, train/total_loss: 20.7160, train/total_loss/avg: 21.4516, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5300, iterations: 5300, max_updates: 236000, lr: 0.00002, ups: 0.30, **time: 05m 31s 215ms**, time_since_start: 17m 48s 608ms, eta: 1633h 55m 57s 200ms
2021-03-12T16:09:05 | mmf.trainers.callbacks.logistics: progress: 5400/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 18.7074, train/total_loss: 20.1549, train/total_loss/avg: 18.7074, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5400, iterations: 5400, max_updates: 236000, lr: 0.00002, ups: 0.30, **time: 05m 38s 447ms**, time_since_start: 23m 27s 055ms, eta: 1668h 52m 58s 330ms
2021-03-12T16:14:47 | mmf.trainers.callbacks.logistics: progress: 5500/236000, train/vqa2/triple_logit_bce: 20.7160, train/vqa2/triple_logit_bce/avg: 20.8974, train/total_loss: 20.7160, train/total_loss/avg: 20.8974, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5500, iterations: 5500, max_updates: 236000, lr: 0.00002, ups: 0.29, **time: 05m 41s 709ms**, time_since_start: 29m 08s 765ms, eta: 1684h 14m 19s 648ms
2021-03-12T16:20:25 | mmf.trainers.callbacks.logistics: progress: 5600/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 18.8222, train/total_loss: 20.1549, train/total_loss/avg: 18.8222, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5600, iterations: 5600, max_updates: 236000, lr: 0.00002, ups: 0.30, **time: 05m 37s 773ms**, time_since_start: 34m 46s 539ms, eta: 1664h 07m 12s 436ms
2021-03-12T16:26:00 | mmf.trainers.callbacks.logistics: progress: 5700/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 18.7029, train/total_loss: 20.1549, train/total_loss/avg: 18.7029, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5700, iterations: 5700, max_updates: 236000, lr: 0.00002, ups: 0.30, time: 05m 35s 088ms, time_since_start: 40m 21s 628ms, eta: 1650h 10m 19s 802ms
2021-03-12T16:31:04 | mmf.trainers.callbacks.logistics: progress: 5800/236000, train/vqa2/triple_logit_bce: 20.1242, train/vqa2/triple_logit_bce/avg: 18.8805, train/total_loss: 20.1242, train/total_loss/avg: 18.8805, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5800, iterations: 5800, max_updates: 236000, lr: 0.00002, ups: 0.33, time: 05m 04s 107ms, time_since_start: 45m 25s 735ms, eta: 1496h 56m 59s 632ms
2021-03-12T16:36:11 | mmf.trainers.callbacks.logistics: progress: 5900/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 19.1537, train/total_loss: 20.1549, train/total_loss/avg: 19.1537, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 5900, iterations: 5900, max_updates: 236000, lr: 0.00002, ups: 0.33, time: 05m 06s 519ms, time_since_start: 50m 32s 255ms, eta: 1508h 10m 14s 517ms
2021-03-12T16:41:25 | mmf.trainers.callbacks.checkpoint: Checkpoint time. Saving a checkpoint.
2021-03-12T16:42:04 | mmf.trainers.callbacks.logistics: progress: 6000/236000, train/vqa2/triple_logit_bce: 20.1549, train/vqa2/triple_logit_bce/avg: 20.0570, train/total_loss: 20.1549, train/total_loss/avg: 20.0570, max mem: 9993.0, experiment: run, epoch: 2, num_updates: 6000, iterations: 6000, max_updates: 236000, lr: 0.00002, ups: 0.28, time: 05m 51s 002ms, time_since_start: 56m 23s 258ms, eta: 1726h 17m 24s 444ms
**2021-03-12T16:42:05 | mmf.trainers.core.training_loop: Evaluation time. Running on full validation set...**

As you can see each of 100 iterations took around 5 minutes. But when it comes to **( Evaluation time. Running on full validation set...)** after 1000 iterations, I waited for **5 hours** and it didn't proceed.

**The gpu consumption during this was**

![Gpu utilization](https://user-images.githubusercontent.com/67015296/110982944-f7242a00-838a-11eb-919c-5d6a3d65cd74.png)

**When I interrupted it, it show the following details**

^CTraceback (most recent call last):
  File "/home/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/new-mmf/mmf-master/mmf_cli/run.py", line 118, in run
    nprocs=config.distributed.world_size,
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(**timeout**)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(**timeout**)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f387d4815f8>>
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 47, in wait
    if not wait([self.sentinel], **timeout**):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(**timeout**)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(**timeout**)
KeyboardInterrupt:
^C

**Could you please help me what is wrong with the model or environment? or if it is a normal behavior then how long do I need to wait for that considering the time for each 100 iterations that is 5 mins approximately. Does it has to do with num_workers or multiple GPUS as my training is working fine but not the Evaluation on validation set**

**python -m torch.utils.collect_env**
Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.18.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 430.64
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.1.6
[pip3] torch==1.6.0+cu101
[pip3] torchtext==0.5.0
[pip3] torchvision==0.7.0+cu101
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.0.130                      0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py36he8ac12f_0
[conda] mkl_fft                   1.2.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.19.2           py36h54aff64_0
[conda] numpy-base                1.19.2           py36hfa32c7d_0
[conda] pytorch-lightning         1.1.6                    pypi_0    pypi
[conda] torch                     1.4.0+cu100              pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.7.0+cu101              pypi_0    pypi

**Comment by vedanuj** [comment]
Hi .. can you try with `run_type=train_val` ?

**Comment by Ifrahmaqsood** [comment]
@vedanuj thank you for your response. I tried with **run_type=train_val** and again waited for 7 hours but no results.

**it ended with same results on interruption**

^CTraceback (most recent call last):
  File "/home/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/new-mmf/mmf-master/mmf_cli/run.py", line 118, in run
    nprocs=config.distributed.world_size,
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f11a6df8c18>>
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f73a907ccf8>>
Traceback (most recent call last):
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
  File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/process.py", line 124, in join
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
    res = self._popen.wait(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 47, in wait
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 47, in wait
    if not wait([self.sentinel], timeout):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    if not wait([self.sentinel], timeout):
  File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
KeyboardInterrupt:
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt:
^C

Any other solutions on how to overcome this issue?

**Comment by vedanuj** [comment]
I am suspecting it might be due to python3.6. Can you try with python 3.7 or 3.8 once? Thanks for your patience!

**Comment by Ifrahmaqsood** [comment]
@vedanuj I tried using both 3.7 and 3.8 and waited for 3-4 hours for each. I also kept on checking gpu utilization. Sometimes it rises to 90% each and other times it is 0% on both. I think that indeed gpus are in use and are loading data. 

Also I am using my own features extracted from **resnet-50 on COCO** dataset and the path to features that I have given
**projects/movie_mcan/configs/vqa2/defaults.yaml** looks like this


dataset_config:
  vqa2:
    depth_first: true
    use_features: true
    zoo_requirements:
      - vqa2.defaults
      - vqa2.grid_features
    features:
      train:
      - /mnt/local_share/Desktop/features
      val:
      - /mnt/local_share/Desktop/features
      test:
      - vqa2/grid_features/features
    annotations:
      train:
      - vqa2/grid_features/annotations/imdb_train2014.npy
      val:
      - vqa2/grid_features/annotations/imdb_val2014.npy
      test:
      - vqa2/grid_features/annotations/imdb_test2015.npy

Can you please let me know how long does it take for evaluation on validation set of **COCO2014** dataset?
Also, as both methods that you suggested didn't work for me what should I do now? any other solution

**Comment by anayavol** [comment]
@vedanuj also please let me know that can I train the model without evaluating it on validation set. Using batch_size=8 and same number of max_iterations=236000 and lr: 5e-05. Will it badly effect the accuracy?

**Comment by Ifrahmaqsood** [comment]
@vedanuj also please let me know can I train my model without evaluating it on validation set. keeping batch_size:8 with default max_updates: 236000 and lr: 5e-05. Will it effect the accuracy badly?

**Comment by Ifrahmaqsood** [comment]
@vedanuj please let me know if you find any solution?

**Comment by vedanuj** [comment]
> also please let me know if I train my model without evaluating it on validation set for now and keeping batch_size:8 with default max_updates: 236000 and lr: 5e-05. Will it effect the accuracy badly?

Batch size 8 will not give you the right accuracy. One way you can use larger batch sizes is by using `training.update_frequency`, which will accumulate gradients after the specified number of forward passes. Please check this for more details : https://github.com/facebookresearch/mmf/blob/master/mmf/configs/defaults.yaml#L51

**Comment by Ifrahmaqsood** [comment]
@apsdehal with batch size=4 num_workers=0 

**CUDA_VISIBLE_DEVICES=0 mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml \model=movie_mcan \dataset=vqa2 \run_type=train \training.num_workers=0**

after 2 hours at **mmf.trainers.core.training_loop: Evaluation time. Running on full validation set...**

**On interruption, my log**

^CTraceback (most recent call last):
  File "/home/anaconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/new-mmf/mmf-master/mmf_cli/run.py", line 122, in run
    main(configuration, predict=predict)
  File "/home/new-mmf/mmf-master/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/home/new-mmf/mmf-master/mmf/trainers/mmf_trainer.py", line 132, in train
    self.training_loop()
  File "/home/new-mmf/mmf-master/mmf/trainers/core/training_loop.py", line 30, in training_loop
    self.run_training_epoch()
  File "/home/new-mmf/mmf-master/mmf/trainers/core/training_loop.py", line 137, in run_training_epoch
    report, meter = self.evaluation_loop(self.val_loader)
  File "/home/new-mmf/mmf-master/mmf/trainers/core/evaluation_loop.py", line 31, in evaluation_loop
    self.update_meter(report, meter)
  File "/home/new-mmf/mmf-master/mmf/trainers/core/reporting.py", line 35, in update_meter
    meter_update_dict, reduced_loss_dict
  File "/home/new-mmf/mmf-master/mmf/trainers/core/reporting.py", line 55, in update_dict
    val = val.item()
KeyboardInterrupt


**I also tried running run_type=val to see the estimated time on validation set after 100 iterations checkpoint**

2021-03-17T01:01:53 | mmf.trainers.mmf_trainer: Starting inference on val set
  0%|                                                                                                                   | 11/53589 [00:32<**42:40:02,  2.87s/it**]
  
**Does it mean that it is taking this much long time for evaluation during the training as well and that's why I am unable to see the results?**

**Comment by ytsheng** [comment]
Hi, thanks for reporting. This may be a recent memory leak that was introduced in the eval run. I am currently looking into this and will provide an answer shortly. We apologize for the inconvenience caused.

**Comment by ytsheng** [comment]
Reporting back, so there does not seem to be a memory leak in the eval loop. The estimated time will be more accurate as more eval iterations are run.

**Comment by Ifrahmaqsood** [comment]
@ytsheng got it. Thank you for your time.

**Comment by naykun** [comment]
Hi, I have met a similar evaluation hanging problem occasionally, especially the 'max_updates' reaches a certain limit. Maybe we should investigate this problem further? I'll provide more information if anyone needs it. I believe there is something wrong with the evaluation process since the hanging always happens when the evaluation performs.
