### ISSUE TITLE
[MoViE+MCAN training] warning: Key vqa2_num_final_outputs is not present

### ISSUE THREAD

**Issue by uehara-mech** [facebookresearch/mmf#856]
I am trying to train MoViE+MCAN model as instructed in https://mmf.sh/docs/projects/movie_mcan .

When I run the training script `mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml model=movie_mcan dataset=vqa2 run_type=train` , I get the following error message.

```
WARNING 2021-04-05T20:27:56 | mmf: Key vqa2_num_final_outputs is not present in registry, returning default value of None
Traceback (most recent call last):
  File "/home/umech/.pyenv/versions/anaconda3-2020.07/envs/transformers/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/home/umech/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/home/umech/mmf/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/home/umech/mmf/trainers/mmf_trainer.py", line 43, in load
    super().load()
  File "/home/umech/mmf/trainers/base_trainer.py", line 30, in load
    self.load_model()
  File "/home/umech/mmf/trainers/mmf_trainer.py", line 94, in load_model
    self.model = build_model(attributes)
  File "/home/umech/mmf/utils/build.py", line 94, in build_model
    model.build()
  File "/home/umech/mmf/models/movie_mcan.py", line 42, in build
    self._init_classifier(self._get_classifier_input_dim())
  File "/home/umech/mmf/models/movie_mcan.py", line 129, in _init_classifier
    self.classifier = ClassifierLayer(
  File "/home/umech/mmf/modules/layers.py", line 116, in __init__
    self.module = TripleLinear(in_dim, out_dim)
  File "/home/umech/mmf/modules/layers.py", line 683, in __init__
    self.linears = nn.ModuleList([nn.Linear(in_dim, out_dim) for _ in range(3)])
  File "/home/umech/mmf/modules/layers.py", line 683, in <listcomp>
    self.linears = nn.ModuleList([nn.Linear(in_dim, out_dim) for _ in range(3)])
  File "/home/umech/.pyenv/versions/anaconda3-2020.07/envs/transformers/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 79, in __init__
    self.weight = Parameter(torch.Tensor(out_features, in_features))
TypeError: new() received an invalid combination of arguments - got (NoneType, int), but expected one of:
 * (*, torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)
```

I suspect that there is something wrong with the config file for MoViE+MCAN ( https://github.com/facebookresearch/mmf/blob/master/mmf/configs/models/movie_mcan/defaults.yaml ).
But I have no idea to fix it...
Could you please help me find out where the problem is?

**Comment by vedanuj** [comment]
Thanks for reporting the issue. We are checking the on our end.

**Comment by apsdehal** [comment]
Please make sure that you are on latest MMF. This issue should be fixed with recent commit 2379d0

**Comment by uehara-mech** [comment]
I have just updated MMF and it worked! Thank you for your help!
