### ISSUE TITLE
Issues saving test predictions in Windows

### ISSUE THREAD

**Issue by gerardoalfredo2** [facebookresearch/mmf#873]
## ❓ Questions and Help
I'm finding some issues with the process to export CSV in Windows.
When I run the next command to do the predictions:
```

mmf_predict config=configs/experiments/defaults.yaml model=concat_vl dataset=hateful_memes run_type=test checkpoint.resume_pretrained=False

```
It returns the next logs:
```
c:\users\admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2021-04-13 18:46:33.346814: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option config to configs/experiments/defaults.yaml
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option model to concat_vl
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option datasets to hateful_memes
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option run_type to test
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option checkpoint.resume_pretrained to False
2021-04-13T18:46:44 | mmf.utils.configuration: Overriding option evaluation.predict to true
2021-04-13T18:46:44 | mmf: Logging to: ./save\train.log
2021-04-13T18:46:44 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=configs/experiments/defaults.yaml', 'model=concat_vl', 'dataset=hateful_memes', 'run_type=test', 'checkpoint.resume_pretrained=False', 'evaluation.predict=true'])
2021-04-13T18:46:44 | mmf_cli.run: Torch version: 1.6.0+cu101
2021-04-13T18:46:44 | mmf.utils.general: CUDA Device 0 is: GeForce RTX 2070
2021-04-13T18:46:44 | mmf_cli.run: Using seed 44152372
2021-04-13T18:46:44 | mmf.trainers.mmf_trainer: Loading datasets
2021-04-13T18:46:46 | mmf.datasets.multi_datamodule: Multitasking disabled by default for single dataset training
2021-04-13T18:46:46 | mmf.datasets.multi_datamodule: Multitasking disabled by default for single dataset training
2021-04-13T18:46:46 | mmf.datasets.multi_datamodule: Multitasking disabled by default for single dataset training
2021-04-13T18:46:46 | mmf.trainers.mmf_trainer: Loading model
2021-04-13T18:46:50 | mmf.trainers.mmf_trainer: Loading optimizer
2021-04-13T18:46:50 | mmf.trainers.mmf_trainer: Loading metrics
WARNING 2021-04-13T18:46:50 | py.warnings: c:\users\admin\anaconda3\lib\site-packages\omegaconf\basecontainer.py:232: UserWarning: cfg.pretty() is deprecated and will be removed in a future version.
Use OmegaConf.to_yaml(cfg)

  category=UserWarning,

WARNING 2021-04-13T18:46:50 | py.warnings: c:\users\admin\anaconda3\lib\site-packages\omegaconf\basecontainer.py:232: UserWarning: cfg.pretty() is deprecated and will be removed in a future version.
Use OmegaConf.to_yaml(cfg)

  category=UserWarning,

2021-04-13T18:46:50 | mmf.trainers.core.evaluation_loop: Starting test inference predictions
2021-04-13T18:46:50 | mmf.common.test_reporter: Predicting for hateful_memes
  0%|                                                                                                                                          | 0/400 [00:00<?, ?it/s]c:\users\admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2021-04-13 18:46:57.445619: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2021-04-13 18:47:14.121896: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2021-04-13 18:47:30.775296: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\users\admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2021-04-13 18:47:48.114387: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll




100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 400/400 [02:04<00:00,  3.20it/s]
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\Scripts\mmf_predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf_cli\predict.py", line 15, in predict
    run(predict=True)
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf_cli\run.py", line 133, in run
    main(configuration, predict=predict)
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf_cli\run.py", line 54, in main
    trainer.inference()
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf\trainers\mmf_trainer.py", line 154, in inference
    self.prediction_loop(dataset)
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf\trainers\core\evaluation_loop.py", line 89, in prediction_loop
    while reporter.next_dataset():
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf\common\test_reporter.py", line 96, in next_dataset
    self.flush_report()
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf\common\test_reporter.py", line 136, in flush_report
    self.csv_dump(filepath)
  File "g:\trainings\cs7643_deeplearning\projects\memes\mmf\mmf\common\test_reporter.py", line 150, in csv_dump
    with PathManager.open(filepath, "w") as f:
  File "c:\users\admin\anaconda3\lib\site-packages\iopath\common\file_io.py", line 922, in open
    path, mode, buffering=buffering, **kwargs
  File "c:\users\admin\anaconda3\lib\site-packages\iopath\common\file_io.py", line 589, in _open
    opener=opener,
OSError: [Errno 22] Invalid argument: 'save\\hateful_memes_concat_vl_44152372\\reports\\hateful_memes_run_test_2021-04-13T18:48:55.csv'
```
I tried with the same command in Ubuntu and it works perfect.
My question is if this is an issue winth windows only.

**Comment by apsdehal** [comment]
Thanks for reporting this bug. Yes, the issue is with windows only because ":" in the filename which is not acceptable in windows. We will look into fixing this.
