### ISSUE TITLE
[Hateful memes] How to train mmbt model on multiple gpus

### ISSUE THREAD

**Issue by dinhanhx** [facebookresearch/mmf#875]
## ❓ Questions and Help

When I run these commands, according to this [doc](https://mmf.sh/docs/notes/concepts/#configuration), I specify `training.data_parallel=True` at the end
```
export CUDA_VISIBLE_DEVICES=0,1
mmf_run config=projects/hateful_memes/configs/mmbt/defaults.yaml model=mmbt dataset=hateful_memes training.data_parallel=True
```
I got this error
```
2021-04-14T18:17:46 | mmf.utils.configuration: Overriding option config to projects/hateful_memes/configs/mmbt/defaults.yaml
2021-04-14T18:17:46 | mmf.utils.configuration: Overriding option model to mmbt
2021-04-14T18:17:46 | mmf.utils.configuration: Overriding option datasets to hateful_memes
Traceback (most recent call last):
  File "/home/anhvd/miniconda3/envs/mmf/bin/mmf_run", line 8, in <module>
    sys.exit(run())
  File "/home/anhvd/miniconda3/envs/mmf/lib/python3.7/site-packages/mmf_cli/run.py", line 91, in run
    configuration = Configuration(args)
  File "/home/anhvd/miniconda3/envs/mmf/lib/python3.7/site-packages/mmf/utils/configuration.py", line 344, in __init__
    self.config = _merge_with_dotlist(self.config, args.opts)
  File "/home/anhvd/miniconda3/envs/mmf/lib/python3.7/site-packages/mmf/utils/configuration.py", line 212, in _merge_with_dotlist
    " configuration at field {}".format(opt, stripped_field)
AttributeError: While updating configuration option training.data_parallel is missing from configuration at field data_parallel
```

How can I fix this? or How should I do to train on multiple gpus?

Thanks for your time

**Comment by apsdehal** [comment]
Hi,
Don't specify `training.data_parallel` in the command. MMF should automatically pick up multiple GPUs if available and should launch a distributed data parallel based run.

**Comment by dinhanhx** [comment]
Okay thank you. I manage to make it work. Shouldn't you to update the documentation?

**Comment by apsdehal** [comment]
Can you point out where you found this command? If possible, can you open up a PR fixing the document. That would super great. Thanks.

**Comment by apsdehal** [comment]
So, you can update the doc to use some other override. For example, `training.max_updates` to update maximum updates that will be done the model.

**Comment by dinhanhx** [comment]
> So, you can update the doc to use some other override. For example, `training.max_updates` to update maximum updates that will be done the model.

I think I don't have time for that.
