### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy.

### ISSUE THREAD

**Issue by dxu312** [facebookresearch/mmf#904]
Hi,
My code below caused the following error. I'm looking up some weight from a dataframe by the id in sample_list. Not sure why I need to convert any tensor to numpy when I just append to the list? Thanks for your advice in advance!

Code:
        weight_dict = pd.read_csv('/mnt/d/memes/data/weight_dict.csv').set_index('id')
        weight = []
        for i in sample_list['id']:
            weight.append(weight_dict.loc[i, 'count'])
        weight = torch.FloatTensor(weight)

Error: 
Traceback (most recent call last):
  File "/home/tsurujan/miniconda3/envs/mmf/bin/mmf_run", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "/mnt/c/Users/xules/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/mnt/c/Users/xules/mmf/mmf_cli/run.py", line 56, in main
    trainer.train()
  File "/mnt/c/Users/xules/mmf/mmf/trainers/mmf_trainer.py", line 138, in train
    self.training_loop()
  File "/mnt/c/Users/xules/mmf/mmf/trainers/core/training_loop.py", line 33, in training_loop
    self.run_training_epoch()
  File "/mnt/c/Users/xules/mmf/mmf/trainers/core/training_loop.py", line 91, in run_training_epoch
    report = self.run_training_batch(batch, num_batches_for_this_update)
  File "/mnt/c/Users/xules/mmf/mmf/trainers/core/training_loop.py", line 164, in run_training_batch
    report = self._forward(batch)
  File "/mnt/c/Users/xules/mmf/mmf/trainers/core/training_loop.py", line 181, in _forward
    model_output = self.model(prepared_batch)
  File "/mnt/c/Users/xules/mmf/mmf/models/base_model.py", line 236, in __call__
    model_output = super().__call__(sample_list, *args, **kwargs)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/Users/xules/mmf/mmf/models/mmbt.py", line 671, in forward
    return self.model(sample_list)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/c/Users/xules/mmf/mmf/models/mmbt.py", line 569, in forward
    weight.append(weight_dict.loc[i, 'count'].cpu())
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 1060, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 831, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 1113, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 1053, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3411, in _convert_listlike_indexer
    keyarr = self._convert_arr_indexer(keyarr)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3429, in _convert_arr_indexer
    keyarr = com.asarray_tuplesafe(keyarr)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/pandas/core/common.py", line 208, in asarray_tuplesafe
    result = np.asarray(values, dtype=dtype)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/tsurujan/miniconda3/envs/mmf/lib/python3.7/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by apsdehal** [comment]
Hi,
Unfortunately, this is unrelated to MMF and rather related to your custom code and there are lot of unknowns here for us to debug this for you. Please use pdb to figure why there is tensor device type mismatch. My guess is that you need to call `.cpu()` on your weight before adding it weights array.

**Comment by dxu312** [comment]
Solved by converting the tensor to list
