### ISSUE TITLE
Issue when running Concat Bert Tutorial

### ISSUE THREAD

**Issue by sidneycb37** [facebookresearch/mmf#914]
## ❓ Questions and Help
I am following the tutorial here (https://mmf.sh/docs/tutorials/concat_bert_tutorial) that outlines how to add a model to MMF. I made no code changes to the example, just copied code to a Jupyter notebook.

However, when I try to run mmf_run, I get the error: 

Traceback (most recent call last):
  File "/usr/local/bin/mmf_run", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/usr/local/lib/python3.7/dist-packages/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/usr/local/lib/python3.7/dist-packages/mmf/trainers/mmf_trainer.py", line 41, in load
    super().load()
  File "/usr/local/lib/python3.7/dist-packages/mmf/trainers/base_trainer.py", line 30, in load
    self.load_model()
  File "/usr/local/lib/python3.7/dist-packages/mmf/trainers/mmf_trainer.py", line 95, in load_model
    self.model = build_model(attributes)
  File "/usr/local/lib/python3.7/dist-packages/mmf/utils/build.py", line 86, in build_model
    raise RuntimeError(f"No model registered for name: {model_name}")
RuntimeError: No model registered for name: concat_bert_tutorial

I've double checked that the line "@registry.register_model("concat_bert_tutorial")" is in my notebook. When I create a new cell to check "registry.get_model_class("concat_bert_tutorial")", it successfully finds the mode and returns "__main__.ConcatBERTTutorial". 

Somehow the call outside of build.py is successful but the call inside of build.py is not.

**Comment by ytsheng** [comment]
Hi @sidneycb37, thanks for using mmf,

When you said "When I try to run mmf_run", you mean you tried to run it in the command line? If so, the command line and the notebook would be under different executable, therefore the command line will not be aware of the registered model, which is why you are able to find it in a new cell but not in the command line.

**Comment by sidneycb37** [comment]
Thank you for your quick response!

They are both being run in the notebook. I've attached my notebook output to this comment

[mmf_ownModelTutorial.pdf](https://github.com/facebookresearch/mmf/files/6404762/mmf_ownModelTutorial.pdf)

**Comment by hivestrung** [comment]
@sidneycb37 you need a __init__.py file and also you will need to set MMF_USER_DIR.

I recommend taking a look at this: https://github.com/apsdehal/hm_example_mmf
