### ISSUE TITLE
error in training the M4C model.

### ISSUE THREAD

**Issue by Harisahmad1881** [facebookresearch/mmf#971]
## ❓ Questions and Help
kindly help to fix that issue.

log

2021-06-16T11:44:57 | mmf.utils.general: Total Parameters: 90850184. Trained Parameters: 90850184
2021-06-16T11:44:57 | mmf.trainers.core.training_loop: Starting training...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmf1\Scripts\mmf_run-script.py", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
  File "f:\mmf\mmf_cli\run.py", line 133, in run
    main(configuration, predict=predict)
  File "f:\mmf\mmf_cli\run.py", line 56, in main
    trainer.train()
  File "f:\mmf\mmf\trainers\mmf_trainer.py", line 142, in train
    self.training_loop()
  File "f:\mmf\mmf\trainers\core\training_loop.py", line 33, in training_loop
    self.run_training_epoch()
  File "f:\mmf\mmf\trainers\core\training_loop.py", line 77, in run_training_epoch
    for idx, batch in enumerate(self.train_loader):
  File "f:\mmf\mmf\datasets\multi_dataset_loader.py", line 199, in __next__
    next_batch = next(self.current_iterator)
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "f:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 231, in _load
    image_id = int(split.split("_")[-1])
ValueError: invalid literal for int() with base 10: 'train\\7ab65fdc58987f37'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\mmf1\lib\site-packages\torch\utils\data\dataset.py", line 219, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "f:\mmf\mmf\datasets\builders\textvqa\dataset.py", line 100, in __getitem__
    features = self.features_db[idx]
  File "f:\mmf\mmf\datasets\databases\features_database.py", line 91, in __getitem__
    return self.get(image_info)
  File "f:\mmf\mmf\datasets\databases\features_database.py", line 99, in get
    return self.from_path(feature_path)
  File "f:\mmf\mmf\datasets\databases\features_database.py", line 107, in from_path
    features, infos = self._get_image_features_and_info(path)
  File "f:\mmf\mmf\datasets\databases\features_database.py", line 80, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "f:\mmf\mmf\datasets\databases\features_database.py", line 65, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "f:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 95, in read
    return self.feat_reader.read(image_feat_path)
  File "f:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 158, in read
    image_info = self._load(image_feat_path)
  File "f:\mmf\mmf\datasets\databases\readers\feature_readers.py", line 238, in _load
    img_id_idx = self.image_id_indices[image_id]
KeyError: b'train\\7ab65fdc58987f37'

**Comment by Harisahmad1881** [comment]
resolved. Thanks
