### ISSUE TITLE
Bert Checkpoint missing weights for mmf_predict on textvqa

### ISSUE THREAD

**Issue by WesRobbins** [facebookresearch/mmf#972]
## 🐛 Bug
Some weights of the model checkpoint at bert-base-uncased were not used when initializing TextBert

## To Reproduce

!mmf_predict config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=test \
    checkpoint.resume_zoo=m4c.textvqa.defaults \
    training.num_workers=2 \
    env.data_dir=/content/drive/MyDrive/data/mmf \
    env.cache_dir=/content/drive/MyDrive/cache/mmf

## Environment

Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.4.0.dev0
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchmetrics==0.3.2
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.5.0
[pip3] torchvision==0.9.1
[conda] Could not collect

### Error Msg
cmalloc: large alloc 5423251456 bytes == 0x55f6c9f4a000 @  0x7fc0818e2887 0x7fbfd26a5173 0x7fbfd268b427 0x7fbfd268bf41 0x7fbfd265a1b3 0x7fbfd267bb6c 0x55f623b208a8 0x55f623b93fd5 0x55f623b8e4ae 0x55f623b21c9f 0x55f623b62d79 0x55f623b5fcc4 0x55f623b20559 0x55f623b944f8 0x55f623b2130a 0x55f623b8f3b5 0x55f623b2130a 0x55f623b8f60e 0x55f623b8e7ad 0x55f623b21a81 0x55f623b64fd9 0x55f623b21ea1 0x55f623b90bb5 0x55f623b8e4ae 0x55f623b21a81 0x55f623b64fd9 0x55f623b20462 0x55f623b93fd5 0x55f623b8e7ad 0x55f623b213ea 0x55f623b8f60e
tcmalloc: large alloc 5423251456 bytes == 0x55f6c9f4a000 @  0x7fc0818e2887 0x7fbfd2725173 0x7fbfd270b427 0x7fbfd270bf41 0x7fbfd26da1b3 0x7fbfd26fbb6c 0x55f623b208a8 0x55f623b93fd5 0x55f623b8e4ae 0x55f623b21c9f 0x55f623b62d79 0x55f623b5fcc4 0x55f623b20559 0x55f623b944f8 0x55f623b2130a 0x55f623b8f3b5 0x55f623b2130a 0x55f623b8f60e 0x55f623b8e7ad 0x55f623b21a81 0x55f623b64fd9 0x55f623b21ea1 0x55f623b90bb5 0x55f623b8e4ae 0x55f623b21a81 0x55f623b64fd9 0x55f623b20462 0x55f623b93fd5 0x55f623b8e7ad 0x55f623b213ea 0x55f623b8f60e
  0% 0/45 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 675) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mmf_predict", line 33, in <module>
    sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_predict')())
  File "/content/mmf/mmf_cli/predict.py", line 15, in predict
    run(predict=True)
  File "/content/mmf/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/content/mmf/mmf_cli/run.py", line 54, in main
    trainer.inference()
  File "/content/mmf/mmf/trainers/mmf_trainer.py", line 158, in inference
    self.prediction_loop(dataset)
  File "/content/mmf/mmf/trainers/core/evaluation_loop.py", line 128, in prediction_loop
    for batch in dataloader:
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 675) exited unexpectedly

### Log

2021-06-16T14:20:15 | INFO | mmf : Logging to: ./save/train.log
2021-06-16T14:20:15 | INFO | mmf_cli.run : Namespace(config_override=None, local_rank=None, opts=['config=projects/m4c/configs/textvqa/defaults.yaml', 'datasets=textvqa', 'model=m4c', 'run_type=test', 'checkpoint.resume_zoo=m4c.textvqa.defaults', 'training.num_workers=2', 'env.data_dir=/content/drive/MyDrive/data/mmf', 'env.cache_dir=/content/drive/MyDrive/cache/mmf', 'evaluation.predict=true'])
2021-06-16T14:20:15 | INFO | mmf_cli.run : Torch version: 1.8.1+cu102
2021-06-16T14:20:15 | INFO | mmf.utils.general : CUDA Device 0 is: Tesla P100-PCIE-16GB
2021-06-16T14:20:15 | INFO | mmf_cli.run : Using seed 15813525
2021-06-16T14:20:15 | INFO | mmf.trainers.mmf_trainer : Loading datasets
2021-06-16T14:20:33 | INFO | mmf.datasets.multi_datamodule : Multitasking disabled by default for single dataset training
2021-06-16T14:20:33 | INFO | mmf.datasets.multi_datamodule : Multitasking disabled by default for single dataset training
2021-06-16T14:20:33 | INFO | mmf.datasets.multi_datamodule : Multitasking disabled by default for single dataset training
2021-06-16T14:20:33 | INFO | mmf.trainers.mmf_trainer : Loading model
2021-06-16T14:20:50 | INFO | mmf.trainers.mmf_trainer : Loading optimizer
2021-06-16T14:20:50 | INFO | mmf.trainers.mmf_trainer : Loading metrics
2021-06-16T14:20:50 | WARNING | py.warnings : /content/mmf/mmf/utils/build.py:414: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

2021-06-16T14:20:50 | WARNING | py.warnings : /content/mmf/mmf/utils/build.py:414: UserWarning: No type for scheduler specified even though lr_scheduler is True, setting default to 'Pythia'
  "No type for scheduler specified even though lr_scheduler is True, "

2021-06-16T14:20:50 | WARNING | py.warnings : /content/mmf/mmf/utils/build.py:420: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

2021-06-16T14:20:50 | WARNING | py.warnings : /content/mmf/mmf/utils/build.py:420: UserWarning: scheduler attributes has no params defined, defaulting to {}.
  warnings.warn("scheduler attributes has no params defined, defaulting to {}.")

2021-06-16T14:20:50 | INFO | mmf.utils.checkpoint : Loading checkpoint
2021-06-16T14:21:32 | WARNING | mmf : Key data_parallel is not present in registry, returning default value of None
2021-06-16T14:21:32 | WARNING | mmf : Key distributed is not present in registry, returning default value of None
2021-06-16T14:21:32 | WARNING | mmf : Key data_parallel is not present in registry, returning default value of None
2021-06-16T14:21:32 | WARNING | mmf : Key distributed is not present in registry, returning default value of None
2021-06-16T14:21:33 | WARNING | mmf.utils.checkpoint : Missing keys ['text_bert.embeddings.position_ids'] in the checkpoint.
If this is not your checkpoint, please open up an issue on MMF GitHub. 
Unexpected keys if any: []
2021-06-16T14:21:33 | WARNING | py.warnings : /content/mmf/mmf/utils/checkpoint.py:304: UserWarning: 'optimizer' key is not present in the checkpoint asked to be loaded. Skipping.
  "'optimizer' key is not present in the "

2021-06-16T14:21:33 | WARNING | py.warnings : /content/mmf/mmf/utils/checkpoint.py:304: UserWarning: 'optimizer' key is not present in the checkpoint asked to be loaded. Skipping.
  "'optimizer' key is not present in the "

2021-06-16T14:21:33 | WARNING | py.warnings : /content/mmf/mmf/utils/checkpoint.py:347: UserWarning: 'lr_scheduler' key is not present in the checkpoint asked to be loaded. Setting lr_scheduler's last_epoch to current_iteration.
  "'lr_scheduler' key is not present in the "

2021-06-16T14:21:33 | WARNING | py.warnings : /content/mmf/mmf/utils/checkpoint.py:347: UserWarning: 'lr_scheduler' key is not present in the checkpoint asked to be loaded. Setting lr_scheduler's last_epoch to current_iteration.
  "'lr_scheduler' key is not present in the "

2021-06-16T14:21:33 | INFO | mmf.utils.checkpoint : Checkpoint loaded.
2021-06-16T14:21:33 | INFO | mmf.utils.checkpoint : Current num updates: 0
2021-06-16T14:21:33 | INFO | mmf.utils.checkpoint : Current iteration: 0
2021-06-16T14:21:33 | INFO | mmf.utils.checkpoint : Current epoch: 0
2021-06-16T14:21:33 | INFO | mmf.trainers.core.evaluation_loop : Starting test inference predictions
2021-06-16T14:21:33 | INFO | mmf.common.test_reporter : Predicting for textvqa
2021-06-16T14:21:37 | INFO | mmf.datasets.processors.processors : Loading fasttext model now from /content/drive/MyDrive/cache/mmf/wiki.en.bin
2021-06-16T14:21:40 | INFO | mmf.datasets.processors.processors : Loading fasttext model now from /content/drive/MyDrive/cache/mmf/wiki.en.bin

**Comment by apsdehal** [comment]
Hi,
The warning is fine and expected but your error looks like that you are running out of memory. Please check memory usage with `htop` to observe that. You can decrease `training.num_workers` to a lower value preferably 0 to avoid this.
