### ISSUE TITLE
Evaluation run on UniT gives error for evaluation run

### ISSUE THREAD

**Issue by Noman-Tanveer** [facebookresearch/mmf#983]
CUDA_VISIBLE_DEVICES=0 python mmf_cli/run.py     config=projects/unit/configs/coco_vqa2/separate_dec.yaml     datasets=detection_visual_genome,detection_coco     model=unit run_type=val training.batch_size=1 checkpoint.resume_zoo=unit.all_8_datasets.shared_dec_with_coco_init

The process loads data and downloads the checkpoint and everything but when training starts. It gives the following Traceback instead of processing the dataset:

Traceback (most recent call last):   
File "mmf_cli/run.py", line 137, in <module>  run()   
File "mmf_cli/run.py", line 133, in run     main(configuration, predict=predict)   
File "mmf_cli/run.py", line 56, in main     trainer.train()   
File "/home/noman_tanveer/mmf/mmf/trainers/mmf_trainer.py", line 138, in train     self.inference()   
File "/home/noman_tanveer/mmf/mmf/trainers/mmf_trainer.py", line 163, in inference     report, meter = self.evaluation_loop(dataset, use_tqdm=True)   
File "/home/noman_tanveer/mmf/mmf/trainers/core/evaluation_loop.py", line 49, in evaluation_loop     model_output = self.model(prepared_batch)   
File "/home/noman_tanveer/mmf/mmf/models/base_model.py", line 267, in __call__     model_output = super().__call__(sample_list, *args, **kwargs)   
File "/home/noman_tanveer/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl     result = self.forward(*input, **kwargs)   
File "/home/noman_tanveer/mmf/mmf/models/unit/unit.py", line 223, in forward task_idx=self.get_task_idx(sample_list.dataset_name),   
File "/home/noman_tanveer/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl     result = self.forward(*input, **kwargs)   
File "/mmf/mmf/models/unit/unit_base_model.py", line 62, in forward     query_embed = self.query_embeds[task_type][dataset_name] 
File "/home/anaconda3/envs/mmf/lib/python3.7/site-packages/torch/nn/modules/container.py", line 288, in __getitem__     return self._modules[key]
KeyError: 'detection_visual_genome'

I've used the mmf environment installed at installation.
 
![Screenshot from 2021-06-24 17-20-51](https://user-images.githubusercontent.com/46514771/123261797-9e7b3600-d510-11eb-853d-c0d902a577f4.png)

**Comment by Noman-Tanveer** [comment]
I used the wrong command.
